import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!;
const KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const CRON=Deno.env.get('CRON_SECRET')||'';
const db=createClient(SUPABASE_URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const SOURCE='https://www.kosik.cz/s1-akce';
const FIRST='https://www.kosik.cz/api/front/page/products/flexible?platform=web&slug=s1-akce&limit=24';
const MORE='https://www.kosik.cz/api/front/products/more';
const ADAPTER='kosik-official-flexible-cursor-v1';
const HEADERS={'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','access-control-allow-headers':'authorization,apikey,content-type,x-cron-secret'};
function reply(x:unknown,s=200){return new Response(JSON.stringify(x),{status:s,headers:HEADERS})}
function auth(r:Request){return (r.headers.get('authorization')||'')===`Bearer ${KEY}`||Boolean(CRON&&r.headers.get('x-cron-secret')===CRON)}
function text(v:unknown){return String(v??'').replace(/\s+/g,' ').trim()}
function norm(v:unknown){return text(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function todayPrague(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Prague',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const o:any={};for(const p of parts)o[p.type]=p.value;return `${o.year}-${o.month}-${o.day}`}
function validTo(label:string,today:string){const m=label.match(/(?:plat[ií]\s+do|\bdo)\s*(\d{1,2})\.\s*(\d{1,2})\./iu);if(!m)return null;const y=Number(today.slice(0,4)),tm=Number(today.slice(5,7)),d=Number(m[1]),mo=Number(m[2]);let yy=y;if(mo<tm-6)yy++;if(mo>tm+6)yy--;return `${yy}-${String(mo).padStart(2,'0')}-${String(d).padStart(2,'0')}`}
function qty(p:any){const q=p?.productQuantity;if(!q)return null;const v=Number(q.value);if(!Number.isFinite(v)||!text(q.unit))return null;return `${text(q.prefix)} ${String(v).replace('.',',')} ${text(q.unit)}`.trim()}
function discount(p:any){const a=Number(p?.price),b=Number(p?.recommendedPrice),c=Number(p?.percentageDiscount);return Number.isFinite(a)&&a>0&&((Number.isFinite(b)&&b>a)||(Number.isFinite(c)&&c>0))}
function makeRow(p:any,today:string){if(!p||!Number.isFinite(Number(p.id))||!text(p.name)||!discount(p)||p.blacklisted===true)return null;const price=Number(p.price),old=Number(p.recommendedPrice);const label=text(p.actionLabel)||text(p?.priceLabels?.[0]?.name);const to=validTo(label,today);if(!to||to<today)return null;const u=text(p.url);const category=text(p?.mainCategory?.name)||null;return {external_id:`kosik:${p.id}`,title:text(p.name),normalized_title:norm(p.name),price,old_price:Number.isFinite(old)&&old>price?old:null,quantity_text:qty(p),valid_from:today,valid_to:to,source_url:u?new globalThis.URL(u,'https://www.kosik.cz').href:SOURCE,source_page:null,product_id:null,image_url:text(p.image).replace('WIDTHxHEIGHTx1_','600x600x1_')||null,confidence:0.995,metadata:{adapter:ADAPTER,parser_version:ADAPTER,kosik_product_id:p.id,percentage_discount:Number.isFinite(Number(p.percentageDiscount))?Number(p.percentageDiscount):null,action_label:label,category,source_category_root:category,source_category_path:category,source_category_items:category?[category]:null,source_category_source:category?'kosik-mainCategory':null,brand:text(p?.brand?.name)||null,price_per_unit:p?.pricePerUnit||null,official_api:true}}}
async function getJson(url:string,options:RequestInit={}){const base:any={'user-agent':'Mozilla/5.0','accept':'application/json','accept-language':'cs-CZ,cs;q=0.9','referer':SOURCE};const extra:any=options.headers||{};const r=await fetch(url,{...options,headers:{...base,...extra}});const raw=await r.text();if(!r.ok)throw new Error(`Košík HTTP ${r.status}: ${raw.slice(0,250)}`);return JSON.parse(raw)}
async function collect(){const first=await getJson(FIRST);let arr=Array.isArray(first?.products?.items)?first.products.items.slice():[];let cursor=first?.products?.cursor||null;const total=Number(first?.products?.totalCount||0);const seen=new Set<string>();let pages=1;while(cursor&&pages<100&&arr.length<2500){const c=String(cursor);if(seen.has(c))throw new Error('Košík cursor loop');seen.add(c);const x=await getJson(MORE,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({cursor:c,limit:24})});const batch=Array.isArray(x?.products)?x.products:[];if(!batch.length){cursor=null;break}arr.push(...batch);cursor=x?.cursor||null;pages++}if(cursor)throw new Error(`Košík pagination nedokončena: ${pages} stran`);const map=new Map<string,any>();for(const p of arr)if(p?.id!=null)map.set(String(p.id),p);return {products:[...map.values()],pages,total}}
async function hash(s:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function errorText(e:unknown){if(e instanceof Error)return e.message;try{return JSON.stringify(e)}catch{return String(e)}}
async function markFailure(message:string){try{const {data:store}=await db.from('stores').select('id').eq('slug','kosik').maybeSingle();if(!store)return;await db.from('store_product_sync_state').update({last_run_at:new Date().toISOString(),last_error:message,last_parser_error:message,health_status:'degraded',health_reason:`Košík synchronizace selhala: ${message}`,is_running:false,run_started_at:null,updated_at:new Date().toISOString(),parser_version:ADAPTER,adapter_name:'sync-kosik-products',adapter_version:'v1'}).eq('store_id',store.id)}catch{}}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:HEADERS});if(req.method!=='POST')return reply({error:'Method not allowed'},405);if(!auth(req))return reply({error:'Unauthorized'},401);try{const body=await req.json().catch(()=>({}));const c=await collect();const today=todayPrague();const map=new Map<string,any>();for(const p of c.products){const r=makeRow(p,today);if(r)map.set(r.external_id,r)}const rows=[...map.values()];if(rows.length<100)throw new Error(`Jen ${rows.length} bezpečných akčních produktů`);const signature=await hash(rows.map(r=>`${r.external_id}|${r.price}|${r.old_price||''}|${r.valid_to}`).sort().join('\n'));if(body.dry_run===true)return reply({ok:true,dry_run:true,api_total:c.total,fetched_unique:c.products.length,pages:c.pages,publishable:rows.length,signature,sample:rows.slice(0,8)});const {data:store,error:storeError}=await db.from('stores').select('id,name').eq('slug','kosik').single();if(storeError||!store)throw storeError||new Error('Košík store nenalezen');const {data:result,error}=await db.rpc('publish_structured_store_offers_with_source_category',{p_store_slug:'kosik',p_adapter:ADAPTER,p_signature:signature,p_rows:rows,p_min_products:100,p_max_products:2500,p_source_document_url:SOURCE,p_parser_version:ADAPTER});if(error)throw error;await db.from('store_product_sync_state').upsert({store_id:store.id,last_run_at:new Date().toISOString(),last_success_at:new Date().toISOString(),last_offer_count:rows.length,expected_offer_count:rows.length,minimum_offer_count:100,last_published_count:rows.length,parser_version:ADAPTER,adapter_name:'sync-kosik-products',adapter_version:'v1',source_type:'official-api',source_category:'sale',last_error:null,last_parser_error:null,health_status:'ok',health_reason:`Košík API: ${rows.length} akčních produktů z ${c.pages} stran.`,is_running:false,run_started_at:null,updated_at:new Date().toISOString(),last_import_id:result?.import_id||null},{onConflict:'store_id'});return reply({ok:true,published:rows.length,api_total:c.total,fetched_unique:c.products.length,pages:c.pages,signature,result});}catch(e){const message=errorText(e);await markFailure(message);return reply({ok:false,error:message},500)}});