import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import * as pdfjs from 'npm:pdfjs-dist@4.10.38/legacy/build/pdf.mjs';

const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const CRON=Deno.env.get('CRON_SECRET')||'';
const LANDING='https://www.itesco.cz/akcni-nabidky/letaky-a-katalogy';
const ADAPTER='tesco-apollo-pdf-v3';
createClient(SUPABASE_URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
const CORS={'access-control-allow-origin':'*','access-control-allow-headers':'authorization,apikey,content-type,x-cron-secret','content-type':'application/json; charset=utf-8'};
const HEADERS={'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/151 Safari/537.36',accept:'text/html,application/xhtml+xml,application/json,*/*;q=0.8','accept-language':'cs-CZ,cs;q=0.9'};
const STOP=new Set(['tesco','vybrane','vybrany','druhy','druh','produkt','produkty','cena','balene','baleny','balena','volny','prodej','clubcard','vice','kus','kusy','gram','kilogram','baleni','akcni','nabidka','nabidky']);

type T={text:string;x:number;y:number;width:number;height:number};
type C={price:number;old_price:number|null;x:number;y:number;kind:'public'|'clubcard'|'unknown';source:string;context:string;norm:string;label:string};
type H={position_id:number;x_percent:number;y_percent:number;pdf_x:number;pdf_y:number;product_refs:string[];product_names:string[];keywords:string[]};

const clean=(v:unknown)=>String(v??'').replace(/\s+/g,' ').trim();
const norm=(v:unknown)=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('cs').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();
const ref=(v:any)=>clean(v?.__ref);
const dist=(ax:number,ay:number,bx:number,by:number)=>Math.hypot(ax-bx,ay-by);
const response=(v:unknown,s=200)=>new Response(JSON.stringify(v),{status:s,headers:CORS});
const allowed=(r:Request)=>r.headers.get('authorization')===`Bearer ${SERVICE}`||Boolean(CRON&&r.headers.get('x-cron-secret')===CRON);
function median(v:number[]){if(!v.length)return null;const s=[...v].sort((a,b)=>a-b),m=Math.floor(s.length/2),n=s.length%2?s[m]:(s[m-1]+s[m])/2;return Math.round(n*10)/10;}
function dateOnly(v:unknown){return String(v??'').match(/^(\d{4}-\d{2}-\d{2})T/)?.[1]||null;}
function dec(v:string){const m=clean(v).match(/^(\d{1,4})[,.](\d{2})(?:\s*Kč)?$/i);if(!m)return null;const n=Number(`${m[1]}.${m[2]}`);return Number.isFinite(n)&&n>0&&n<10000?n:null;}
function words(names:string[]){const out=new Set<string>();for(const n of names)for(const w of norm(n).split(' '))if(w.length>=4&&!STOP.has(w)&&!/^\d+$/.test(w))out.add(w);return [...out];}
function nextData(html:string){const a=html.indexOf('<script id="__NEXT_DATA__"');if(a<0)throw new Error('Tesco viewer neobsahuje __NEXT_DATA__.');const b=html.indexOf('>',a),c=html.indexOf('</script>',b+1);if(b<0||c<0)throw new Error('Tesco __NEXT_DATA__ nelze vyříznout.');return JSON.parse(html.slice(b+1,c));}
async function fetchText(url:string){const r=await fetch(url,{headers:HEADERS,redirect:'follow',signal:AbortSignal.timeout(30000)}),text=await r.text();if(!r.ok)throw new Error(`Tesco HTML HTTP ${r.status}`);return{text,url:r.url};}
async function viewerUrl(){const h=await fetchText(`${LANDING}?_slevao=${Date.now()}`),m=h.text.match(/href=["']([^"']*\/hypermarkety\/tesco-letak-\d{4}-\d{2}-\d{2}\/1)["']/i);if(!m)throw new Error('Tesco landing neobsahuje aktuální hypermarketový viewer.');return new URL(m[1].replace(/&amp;/g,'&'),LANDING).toString();}
function apollo(html:string){const pp=nextData(html)?.props?.pageProps||{},state=pp.__APOLLO_STATE__||{};const ls=Object.entries(state).filter(([k,v]:any)=>k.startsWith('Leaflet:')&&v?.type==='HM'&&Array.isArray(v?.pages)).map(([key,v]:any)=>({key,...v}));if(!ls.length)throw new Error('Tesco Apollo state neobsahuje HM leták.');ls.sort((a:any,b:any)=>String(b.validFrom||'').localeCompare(String(a.validFrom||'')));const leaflet:any=ls[0],pages=leaflet.pages.map(ref).filter(Boolean).map((r:string)=>({ref:r,...(state[r]||{})})).filter((p:any)=>p.__typename==='LeafletMetadataPage').sort((a:any,b:any)=>Number(a.page)-Number(b.page));const images=pages.map((p:any)=>clean(p.pagePNG)).filter((u:string)=>/^https:\/\//i.test(u));const posRefs=pages.flatMap((p:any)=>(p.positions||[]).map(ref)).filter(Boolean),positions=posRefs.map((r:string)=>({ref:r,...(state[r]||{})})).filter((x:any)=>x.__typename==='LeafletMetadataPagePosition');const prs=new Set<string>();for(const p of positions)for(const x of p.products||[]){const r=ref(x);if(r)prs.add(r);}const products=[...prs].map(r=>({ref:r,...(state[r]||{})})).filter((x:any)=>x.__typename==='LeafletProduct');return{config:pp.config||{},state,leaflet,pages,images,positions,products};}
function around(t:T[],x:number,y:number,xr:number,yr:number){return clean(t.filter(q=>Math.abs(q.x-x)<=xr&&Math.abs(q.y-y)<=yr).sort((a,b)=>Math.abs(b.y-a.y)>4?b.y-a.y:a.x-b.x).map(q=>q.text).join(' '));}
function kind(label:string):C['kind']{const n=norm(label),pub=n.lastIndexOf('cena pro vsechny'),club=Math.max(n.lastIndexOf('clubcard cena'),n.lastIndexOf('s clubcard'));if(pub<0&&club<0)return'unknown';return club>pub?'clubcard':'public';}
function candidates(t:T[]):C[]{const out:C[]=[];const cents=t.filter(q=>/^\d{2}$/.test(q.text)&&q.height>=7&&q.height<=16),whole=t.filter(q=>/^\d{1,4}$/.test(q.text)&&q.height>=17&&q.width>=10),decimal=t.map(q=>({q,v:dec(q.text)})).filter(x=>x.v!==null) as {q:T;v:number}[];for(const w of whole){const n=Number(w.text);if(!Number.isFinite(n)||n<=0||n>9999)continue;const c=cents.filter(q=>q.x>=w.x+w.width-4&&q.x<=w.x+w.width+24&&q.y>=w.y+2&&q.y<=w.y+16).sort((a,b)=>dist(w.x,w.y,a.x,a.y)-dist(w.x,w.y,b.x,b.y))[0];if(!c)continue;const price=Math.round((n+Number(c.text)/100)*100)/100;const old=decimal.filter(x=>x.v>price&&Math.abs(x.q.x-w.x)<=34&&x.q.y>=w.y+10&&x.q.y<=w.y+58).sort((a,b)=>Math.abs(a.q.y-w.y)-Math.abs(b.q.y-w.y))[0];const context=around(t,w.x,w.y,115,95).slice(0,1200),label=around(t,w.x,w.y,72,48).slice(0,600);out.push({price,old_price:old?.v||null,x:Math.round(w.x*10)/10,y:Math.round(w.y*10)/10,kind:kind(label),source:`${w.text}+${c.text}`,context,norm:norm(context),label});}const seen=new Set<string>();return out.filter(x=>{const k=`${x.price}|${x.x}|${x.y}`;if(seen.has(k))return false;seen.add(k);return true;});}
function hotspots(a:any,page:any,w:number,h:number):H[]{const out:H[]=[];for(const pr of (page.positions||[]).map(ref).filter(Boolean)){const p=a.state[pr];if(!p||!Array.isArray(p.products)||!p.products.length)continue;const xp=Number(p.calculatedPositionX),yp=Number(p.calculatedPositionY);if(!Number.isFinite(xp)||!Number.isFinite(yp))continue;const product_refs=p.products.map(ref).filter(Boolean),product_names=product_refs.map((r:string)=>clean(a.state[r]?.promoOfferName||a.state[r]?.product?.productName)).filter(Boolean);if(!product_names.length)continue;out.push({position_id:Number(p.id),x_percent:Math.round(xp*100)/100,y_percent:Math.round(yp*100)/100,pdf_x:w*xp/100,pdf_y:h-h*yp/100,product_refs,product_names,keywords:words(product_names)});}return out;}
function metrics(h:H,c:C){const dx=h.pdf_x-c.x,dy=h.pdf_y-c.y,sp=Math.hypot(dx*.9,dy),cw=new Set(c.norm.split(' ').filter(Boolean)),matched=h.keywords.filter(w=>cw.has(w)),bonus=Math.min(130,matched.length*65);return{cost:Math.max(0,sp-bonus),sp,matched};}
function hungarian(cost:number[][]){const n=cost.length,m=cost[0]?.length||0;if(!n||!m)return[];if(n>m)throw new Error(`Hungarian ${n}>${m}`);const u=Array(n+1).fill(0),v=Array(m+1).fill(0),p=Array(m+1).fill(0),way=Array(m+1).fill(0);for(let i=1;i<=n;i++){p[0]=i;let j0=0;const minv=Array(m+1).fill(Infinity),used=Array(m+1).fill(false);do{used[j0]=true;const i0=p[j0];let delta=Infinity,j1=0;for(let j=1;j<=m;j++)if(!used[j]){const cur=cost[i0-1][j-1]-u[i0]-v[j];if(cur<minv[j]){minv[j]=cur;way[j]=j0;}if(minv[j]<delta){delta=minv[j];j1=j;}}for(let j=0;j<=m;j++)if(used[j]){u[p[j]]+=delta;v[j]-=delta;}else minv[j]-=delta;j0=j1;}while(p[j0]!==0);do{const j1=way[j0];p[j0]=p[j1];j0=j1;}while(j0!==0);}const a=Array(n).fill(-1);for(let j=1;j<=m;j++)if(p[j]>0&&p[j]<=n)a[p[j]-1]=j-1;return a;}
function assign(hs:H[],cs:C[]){if(!hs.length)return{sparse:false,rows:[] as any[]};if(cs.length<Math.ceil(hs.length*.55))return{sparse:true,rows:hs.map(h=>({...h,assigned:false,confidence:'none',rejection_reason:'sparse_or_special_page',candidate:null}))};const real=cs.length,work:(C|null)[]=[...cs];while(work.length<hs.length)work.push(null);const a=hungarian(hs.map(h=>work.map(c=>c?metrics(h,c).cost:320)));return{sparse:false,rows:hs.map((h,i)=>{const ci=a[i],c=ci>=0&&ci<real?cs[ci]:null;if(!c)return{...h,assigned:false,confidence:'none',rejection_reason:'no_candidate',candidate:null};const m=metrics(h,c),confidence=m.matched.length>=2||m.sp<=75?'high':m.matched.length>=1||m.sp<=125?'medium':m.sp<=175?'low':'reject';return{...h,assigned:confidence!=='reject',confidence,rejection_reason:confidence==='reject'?'distance':null,assignment_cost:Math.round(m.cost*10)/10,spatial_distance:Math.round(m.sp*10)/10,semantic_count:m.matched.length,semantic_words:m.matched,candidate_index:ci,candidate:{price:c.price,old_price:c.old_price,kind:c.kind,x:c.x,y:c.y,context:c.context.slice(0,500),label_context:c.label.slice(0,300)}};})};}
async function probe(pdf:string,viewer:string,a:any,start:number,count:number,details:boolean){const r=await fetch(pdf,{headers:{...HEADERS,accept:'application/pdf,*/*;q=0.8',referer:viewer},redirect:'follow',signal:AbortSignal.timeout(45000)});if(!r.ok)throw new Error(`Tesco PDF HTTP ${r.status}`);const ct=clean(r.headers.get('content-type')).toLowerCase(),bytes=new Uint8Array(await r.arrayBuffer());if(!ct.includes('pdf')||bytes.length<100000||bytes.length>80*1024*1024)throw new Error(`Tesco PDF má neplatný typ/velikost: ${ct}, ${bytes.length} B.`);const doc=await pdfjs.getDocument({data:bytes,disableWorker:true,useSystemFonts:true}).promise,first=Math.max(1,Math.min(doc.numPages,start)),last=Math.min(doc.numPages,first+Math.max(1,Math.min(12,count))-1),pages:any[]=[],dists:number[]=[];let H=0,Cn=0,A=0,Hi=0,M=0,L=0,R=0,S=0,SP=0;for(let no=first;no<=last;no++){const page=await doc.getPage(no),tc:any=await page.getTextContent(),t:T[]=(tc.items||[]).filter((x:any)=>typeof x.str==='string'&&clean(x.str)).map((x:any)=>({text:clean(x.str),x:Number(x.transform?.[4]||0),y:Number(x.transform?.[5]||0),width:Number(x.width||0),height:Math.abs(Number(x.height||x.transform?.[3]||x.transform?.[0]||0))})),w=Number(page.view?.[2]||0),h=Number(page.view?.[3]||0),cs=candidates(t),ap=a.pages.find((x:any)=>Number(x.page)===no),hs=ap?hotspots(a,ap,w,h):[],as=assign(hs,cs),rows=as.rows;if(as.sparse)SP++;H+=hs.length;Cn+=cs.length;for(const x of rows){if(x.assigned){A++;dists.push(Number(x.spatial_distance||0));}else R++;if(x.confidence==='high')Hi++;if(x.confidence==='medium')M++;if(x.confidence==='low')L++;S+=Number(x.semantic_count||0);}const ps:any={page:no,token_count:t.length,hotspot_count:hs.length,candidate_price_count:cs.length,public_candidate_count:cs.filter(x=>x.kind==='public').length,clubcard_candidate_count:cs.filter(x=>x.kind==='clubcard').length,unknown_candidate_count:cs.filter(x=>x.kind==='unknown').length,assigned_count:rows.filter((x:any)=>x.assigned).length,high_count:rows.filter((x:any)=>x.confidence==='high').length,medium_count:rows.filter((x:any)=>x.confidence==='medium').length,low_count:rows.filter((x:any)=>x.confidence==='low').length,rejected_count:rows.filter((x:any)=>!x.assigned).length,sparse_or_special:as.sparse};if(details){ps.assignments=rows.slice(0,70);ps.unmatched_price_candidates=cs.map((candidate,index)=>({candidate:{...candidate,context:candidate.context.slice(0,500)},index})).filter(({index})=>!rows.some((x:any)=>x.candidate_index===index)).slice(0,30);}pages.push(ps);}return{pdf_bytes:bytes.length,pdf_pages:doc.numPages,start_page:first,end_page:last,probed_pages:last-first+1,probe_hotspots:H,probe_price_candidates:Cn,probe_assigned:A,probe_high:Hi,probe_medium:M,probe_low:L,probe_rejected:R,probe_semantic_hits:S,sparse_or_special_pages:SP,median_accepted_spatial_distance:median(dists),pages};}

Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method!=='POST')return response({error:'Method not allowed'},405);if(!allowed(req))return response({error:'Unauthorized'},401);try{const body=await req.json().catch(()=>({})),viewer=body.viewer_url?String(body.viewer_url):await viewerUrl(),vh=await fetchText(viewer),a=apollo(vh.text),pdf=clean(a.leaflet.leafletUrl);if(!/^https:\/\/digitalcontent\.api\.tesco\.com\//i.test(pdf))throw new Error('Tesco Apollo nevrátilo oficiální PDF URL.');if(a.pages.length<8||a.images.length!==a.pages.length)throw new Error(`Tesco Apollo má neúplné stránky: ${a.pages.length}/${a.images.length}.`);const p=await probe(pdf,viewer,a,Number(body.start_page||1),Number(body.probe_pages||3),body.details===true);return response({ok:true,dry_run:true,adapter:ADAPTER,viewer_url:viewer,apollo_url:clean(a.config?.APOLLO_URL),leaflet_id:a.leaflet.id,leaflet_type:a.leaflet.type,valid_from:dateOnly(a.leaflet.validFrom),valid_to:dateOnly(a.leaflet.validTo),page_count:a.pages.length,page_image_count:a.images.length,hotspot_count:a.positions.length,referenced_product_count:a.products.length,apollo_state_object_count:Object.keys(a.state).length,pdf_url:pdf,...p});}catch(e){return response({error:e instanceof Error?e.message:String(e),adapter:ADAPTER},500);}});
