import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!,KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,CRON=Deno.env.get('CRON_SECRET')||'';
const db=createClient(SUPABASE_URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}}),SOURCE='https://www.dek.cz/produkty/vypis/1642-akcni-nabidky',ADAPTER='dek-official-action-html-v3';
const H={'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','access-control-allow-headers':'authorization,apikey,content-type,x-cron-secret'};
const json=(v:unknown,s=200)=>new Response(JSON.stringify(v),{status:s,headers:H});
async function allowed(r:Request){const t=(r.headers.get('authorization')||'').replace(/^Bearer\s+/i,'').trim();if(t===KEY||(CRON&&r.headers.get('x-cron-secret')===CRON))return true;if(!t)return false;const {data}=await db.auth.getUser(t);return ['admin','editor'].includes(String(data.user?.app_metadata?.role||'').toLowerCase())}
function clean(v:string){return v.replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
function norm(v:string){return v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function today(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Prague',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),x=Object.fromEntries(p.map(y=>[y.type,y.value]));return `${x.year}-${x.month}-${x.day}`}
function plus(v:string){const d=new Date(`${v}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+1);return d.toISOString().slice(0,10)}
function money(v:string){const n=Number(clean(v).replace(/\s/g,'').replace(',','.').replace(/[^0-9.]/g,''));return Number.isFinite(n)&&n>0?n:null}
async function hash(v:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function parse(html:string){const d=today(),to=plus(d),rows:any[]=[];for(const block of html.split(/data-product-id="/).slice(1)){const id=block.match(/^(\d+)"/)?.[1]||'';if(!/^\d+$/.test(id))continue;const href=block.match(/class="comd-product-view--long__title"\s+href="([^"]+)"/)?.[1]||block.match(/href="([^\"]+\/produkty\/detail\/[^\"]+)"/)?.[1]||'';const title=clean(block.match(/data-playwright="product-detail-link"[^>]*>([\s\S]*?)<\/a>/)?.[1]||'');const image=block.match(/<img src="(https:\/\/cdn1\.idek\.cz\/[^"]+)"[^>]*loading="lazy"/)?.[1]||'';const high=block.match(/<div class="price-vat highlight">[\s\S]*?<div>([\d\s]+)<span>,(\d{2})<\/span><\/div>/);if(!title||!href||!high)continue;const price=Number(`${high[1].replace(/\s/g,'')}.${high[2]}`);if(!Number.isFinite(price)||price<2||price>200000)continue;const strike=block.match(/<span class="strike"><em>([\s\S]*?)<\/em><\/span>/)?.[1]||'';const old=money(strike);const sourceUrl=new globalThis.URL(href,'https://www.dek.cz').toString();const availability=clean(block.match(/<div class="warehouse-state [^"]+"[^>]*>([\s\S]*?)<\/div>/)?.[1]||'');rows.push({external_id:`dek:${id}`,title,normalized_title:norm(title),price,old_price:old&&old>price?old:null,valid_from:d,valid_to:to,source_url:sourceUrl,image_url:image||null,confidence:0.99,metadata:{adapter:ADAPTER,dek_product_id:id,availability:availability||null,price_policy:'official_highlight_price_with_vat',reference_price_policy:old&&old>price?'official_strike_price_with_vat':'none',validity_policy:'daily_snapshot_plus_one_day'}})}return [...new Map(rows.map(r=>[r.external_id,r])).values()]}
async function fetchSource(){let last='';for(let attempt=1;attempt<=2;attempt++){const c=new AbortController(),timer=setTimeout(()=>c.abort(),25000);try{const res=await fetch(SOURCE,{headers:{'user-agent':'Mozilla/5.0','accept':'text/html','accept-language':'cs-CZ,cs;q=0.9'},redirect:'follow',signal:c.signal});if(!res.ok)throw new Error(`DEK HTTP ${res.status}`);return await res.text()}catch(e){last=e instanceof Error?e.message:String(e);if(attempt<2)await new Promise(r=>setTimeout(r,1200))}finally{clearTimeout(timer)}}throw new Error(`DEK source failed after 2 attempts: ${last}`)}
async function setError(message:string){const {data:store}=await db.from('stores').select('id').eq('slug','dek').maybeSingle();if(!store?.id)return;await db.from('store_product_sync_state').upsert({store_id:store.id,health_status:'error',health_reason:'DEK automatický produktový sync selhal; předchozí ověřené nabídky zůstaly zachované.',last_error:message.slice(0,1800),last_parser_error:message.slice(0,1800),last_run_at:new Date().toISOString(),is_running:false,updated_at:new Date().toISOString()},{onConflict:'store_id'})}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:H});if(req.method!=='POST')return json({error:'Method not allowed'},405);if(!(await allowed(req)))return json({error:'Unauthorized'},401);try{const body=await req.json().catch(()=>({}));const rows=parse(await fetchSource());if(rows.length<20||rows.length>500)throw new Error(`DEK parser našel ${rows.length} položek mimo bezpečný rozsah 20–500.`);const signature=await hash(rows.map(r=>`${r.external_id}|${r.price}|${r.old_price||''}|${r.valid_from}|${r.valid_to}|${r.source_url}`).sort().join('\n'));if(body.dry_run===true)return json({ok:true,dry_run:true,publishable:rows.length,with_old_price:rows.filter(r=>r.old_price).length,with_detail_url:rows.filter(r=>/\/produkty\/detail\//.test(r.source_url)).length,samples:rows.slice(0,5)});const {data:store,error:se}=await db.from('stores').select('id').eq('slug','dek').single();if(se||!store)throw se||new Error('DEK store missing');const {data:src}=await db.from('leaflet_sources').select('id').eq('store_id',store.id).eq('source_url',SOURCE).maybeSingle();if(src)await db.from('leaflet_sources').update({is_active:true,source_type:'html',adapter_key:'dek-official-action-html-v3',extraction_strategy:'structured_html',last_checked_at:new Date().toISOString(),last_success_at:new Date().toISOString(),last_error:null}).eq('id',src.id);const {data:result,error}=await db.rpc('publish_structured_store_offers',{p_store_slug:'dek',p_adapter:'dek-official-action-html-v1',p_signature:signature,p_rows:rows,p_min_products:20,p_max_products:500,p_source_document_url:SOURCE,p_parser_version:ADAPTER});if(error)throw new Error(error.message||JSON.stringify(error));await db.from('store_product_sync_state').upsert({store_id:store.id,health_status:'ok',health_reason:`DEK: ${rows.length} ověřených akčních nabídek z oficiálního HTML zdroje.`,last_error:null,last_parser_error:null,last_run_at:new Date().toISOString(),last_success_at:new Date().toISOString(),last_offer_count:rows.length,last_published_count:rows.length,parser_version:ADAPTER,adapter_name:'sync-dek-products',adapter_version:'v5',source_type:'official-html-products',is_running:false,updated_at:new Date().toISOString()},{onConflict:'store_id'});return json({ok:true,published:rows.length,with_old_price:rows.filter(r=>r.old_price).length,with_detail_url:rows.filter(r=>/\/produkty\/detail\//.test(r.source_url)).length,signature,result})}catch(e){const m=e instanceof Error?e.message:String(e);await setError(m);return json({error:m,code:'DEK_SYNC_FAILED'},500)}});