import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const CRON=Deno.env.get('CRON_SECRET')||'';
const db=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
const CORS={'access-control-allow-origin':'*','access-control-allow-headers':'authorization,apikey,content-type,x-cron-secret','access-control-allow-methods':'POST,OPTIONS','content-type':'application/json; charset=utf-8'};
const HEADERS={'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/150 Safari/537.36',accept:'text/html,application/json,*/*;q=0.8','accept-language':'cs-CZ,cs;q=0.9'};
const SOURCE='https://jysk.cz/campaign';
const SALE='https://jysk.cz/vyprodej';
const PRODUCT_JSON='https://jysk.cz/products/json/main_cz/';

function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:CORS});}
async function allowed(request:Request){const raw=request.headers.get('authorization')||'',token=raw.replace(/^Bearer\s+/i,'').trim();if(token===SERVICE)return true;if(CRON&&request.headers.get('x-cron-secret')===CRON)return true;if(!token)return false;const{data,error}=await db.auth.getUser(token);return!error&&!!data.user&&['admin','editor'].includes(String(data.user.app_metadata?.role||'').toLowerCase());}
async function fetchAny(url:string,timeout=25000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const r=await fetch(url,{headers:HEADERS,redirect:'follow',signal:controller.signal});const text=await r.text();return{text,url:r.url,status:r.status,contentType:r.headers.get('content-type')||''}}finally{clearTimeout(timer)}}
async function fetchText(url:string,timeout=25000){const r=await fetchAny(url,timeout);if(r.status<200||r.status>=300)throw new Error(`${new URL(url).hostname} HTTP ${r.status}`);return r}
function decode(value:string){return value.replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&nbsp;|&#160;/gi,' ').replace(/\\u002F/gi,'/').replace(/\\u0026/gi,'&');}
function snippets(html:string,needle:RegExp,limit=80){const out:string[]=[];const flags=needle.flags.includes('g')?needle.flags:needle.flags+'g';for(const m of html.matchAll(new RegExp(needle.source,flags))){if(out.length>=limit)break;const i=m.index||0;out.push(decode(html.slice(Math.max(0,i-220),Math.min(html.length,i+520))).replace(/\s+/g,' '));}return out;}
function productLinks(html:string,base:string){const set=new Set<string>();for(const m of html.matchAll(/href=["']([^"']+)["']/gi)){const raw=decode(m[1]);if(/(?:\/produkt\/|\/product\/)/i.test(raw)){try{set.add(new URL(raw,base).toString())}catch{}}}return[...set].slice(0,200);}
function productIds(html:string){const set=new Set<string>();for(const m of html.matchAll(/(?:articleId|article_id|productId|product_id|data-product-id|data-article-id)[^0-9]{0,20}(\d{5,12})/gi))set.add(m[1]);return[...set].slice(0,500);}

Deno.serve(async request=>{if(request.method==='OPTIONS')return new Response('ok',{headers:CORS});if(request.method!=='POST')return json({error:'Method not allowed'},405);if(!(await allowed(request)))return json({error:'Unauthorized'},401);try{const body=await request.json().catch(()=>({}));if(body.dry_run!==true)return json({error:'JYSK produktová publikace zatím není povolena; použij dry_run.'},409);const [campaign,sale,productJson]=await Promise.all([fetchText(SOURCE),fetchText(SALE),fetchAny(PRODUCT_JSON)]);const campaignHtml=campaign.text,saleHtml=sale.text;const solrUrl=decode(campaignHtml.match(/\\?"solrUrl\\?"\s*:\s*\\?"([^"\\]+(?:\\.[^"\\]*)*)/i)?.[1]||PRODUCT_JSON).replace(/\\\//g,'/');const jsonLd=[...saleHtml.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)].slice(0,30).map(x=>decode(x[1]).trim()).filter(Boolean);const publications=[...new Set([...campaignHtml.matchAll(/https:\/\/ipaper\.ipapercms\.dk\/jysk\/cz\/CampaignPaper\/[a-z0-9_]+/gi)].map(x=>x[0]))];return json({ok:true,dry_run:true,campaign:{url:campaign.url,bytes:campaignHtml.length,publications},sale:{url:sale.url,bytes:saleHtml.length,product_links:productLinks(saleHtml,SALE),product_ids:productIds(saleHtml),json_ld_count:jsonLd.length,json_ld_samples:jsonLd.slice(0,6).map(x=>x.slice(0,8000)),price_snippets:snippets(saleHtml,/(?:price|currentPrice|campaignPrice|salesPrice|articleId|productId|data-product)/gi,80)},product_json:{configured_url:solrUrl,request_url:productJson.url,status:productJson.status,content_type:productJson.contentType,bytes:productJson.text.length,sample:decode(productJson.text.slice(0,12000))}});}catch(error){return json({error:error instanceof Error?error.message:String(error),code:'JYSK_PRODUCT_DRY_RUN_FAILED'},500)}});
