import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const CRON=Deno.env.get('CRON_SECRET')||'';
const db=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
const CORS={'access-control-allow-origin':'*','access-control-allow-headers':'authorization,apikey,content-type,x-cron-secret','access-control-allow-methods':'POST,OPTIONS','content-type':'application/json; charset=utf-8'};
const HEADERS={'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/150 Safari/537.36',accept:'text/html,application/xhtml+xml,*/*;q=0.8','accept-language':'cs-CZ,cs;q=0.9'};
const SOURCE='https://jysk.cz/campaign';

function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:CORS});}
async function allowed(request:Request){const raw=request.headers.get('authorization')||'',token=raw.replace(/^Bearer\s+/i,'').trim();if(token===SERVICE)return true;if(CRON&&request.headers.get('x-cron-secret')===CRON)return true;if(!token)return false;const{data,error}=await db.auth.getUser(token);return!error&&!!data.user&&['admin','editor'].includes(String(data.user.app_metadata?.role||'').toLowerCase());}
async function fetchText(url:string,timeout=25000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const r=await fetch(url,{headers:HEADERS,redirect:'follow',signal:controller.signal});const text=await r.text();if(!r.ok)throw new Error(`${new URL(url).hostname} HTTP ${r.status}`);return{text,url:r.url,status:r.status}}finally{clearTimeout(timer)}}
function decode(value:string){return value.replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&nbsp;|&#160;/gi,' ').replace(/\\u002F/gi,'/');}
function snippets(html:string,needle:RegExp,limit=50){const out:string[]=[];for(const m of html.matchAll(new RegExp(needle.source,needle.flags.includes('g')?needle.flags:needle.flags+'g'))){if(out.length>=limit)break;const i=m.index||0;out.push(decode(html.slice(Math.max(0,i-180),Math.min(html.length,i+360))).replace(/\s+/g,' '));}return out;}
function urls(html:string){const set=new Set<string>();for(const m of html.matchAll(/(?:href|src)=["']([^"']+)["']/gi)){const raw=decode(m[1]);if(/(?:product|campaign|api|graphql|json|ajax|search|price|listing|recommend)/i.test(raw)){try{set.add(new URL(raw,SOURCE).toString())}catch{}}}return[...set].slice(0,160);}
function scripts(html:string){const set=new Set<string>();for(const m of html.matchAll(/<script[^>]+src=["']([^"']+)["']/gi)){try{set.add(new URL(decode(m[1]),SOURCE).toString())}catch{}}return[...set].slice(0,100);}

Deno.serve(async request=>{if(request.method==='OPTIONS')return new Response('ok',{headers:CORS});if(request.method!=='POST')return json({error:'Method not allowed'},405);if(!(await allowed(request)))return json({error:'Unauthorized'},401);try{const body=await request.json().catch(()=>({}));if(body.dry_run!==true)return json({error:'JYSK produktová publikace zatím není povolena; použij dry_run.'},409);const page=await fetchText(SOURCE);const html=page.text;const jsonLd=[...html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)].slice(0,20).map(x=>decode(x[1]).trim()).filter(Boolean);const productLinks=new Set<string>();for(const m of html.matchAll(/href=["']([^"']+)["']/gi)){const raw=decode(m[1]);if(/\/produkt\//i.test(raw)||/\/product\//i.test(raw)){try{productLinks.add(new URL(raw,SOURCE).toString())}catch{}}}
 const publications=[...new Set([...html.matchAll(/https:\/\/ipaper\.ipapercms\.dk\/jysk\/cz\/CampaignPaper\/[a-z0-9_]+/gi)].map(x=>x[0]))];return json({ok:true,dry_run:true,source:page.url,html_bytes:html.length,product_links:[...productLinks].slice(0,120),product_link_count:productLinks.size,json_ld_count:jsonLd.length,json_ld_samples:jsonLd.slice(0,4).map(x=>x.slice(0,5000)),interesting_urls:urls(html),script_urls:scripts(html),publications,price_snippets:snippets(html,/(?:price|currentPrice|campaignPrice|salesPrice|productId|product_number|product-number)/gi,60)});}catch(error){return json({error:error instanceof Error?error.message:String(error),code:'JYSK_PRODUCT_DRY_RUN_FAILED'},500)}});
