import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const CRON=Deno.env.get('CRON_SECRET')||'';
const db=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
const CORS={'access-control-allow-origin':'*','access-control-allow-headers':'authorization,apikey,content-type,x-cron-secret','access-control-allow-methods':'POST,OPTIONS','content-type':'application/json; charset=utf-8'};
const HEADERS={'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/150 Safari/537.36',accept:'text/html,application/json,*/*;q=0.8','accept-language':'cs-CZ,cs;q=0.9'};
const SOURCE='https://jysk.cz/campaign';
const SALE='https://jysk.cz/vyprodej';

function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:CORS});}
async function allowed(request:Request){const raw=request.headers.get('authorization')||'',token=raw.replace(/^Bearer\s+/i,'').trim();if(token===SERVICE)return true;if(CRON&&request.headers.get('x-cron-secret')===CRON)return true;if(!token)return false;const{data,error}=await db.auth.getUser(token);return!error&&!!data.user&&['admin','editor'].includes(String(data.user.app_metadata?.role||'').toLowerCase());}
async function fetchText(url:string,timeout=25000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const r=await fetch(url,{headers:HEADERS,redirect:'follow',signal:controller.signal});const text=await r.text();if(!r.ok)throw new Error(`${new URL(url).hostname} HTTP ${r.status}`);return{text,url:r.url}}finally{clearTimeout(timer)}}
function decode(value:string){let out=value;for(let i=0;i<3;i++){const next=out.replace(/&amp;/gi,'&').replace(/&quot;|&#34;|&#x22;/gi,'"').replace(/&#39;|&apos;|&#x27;/gi,"'").replace(/&nbsp;|&#160;/gi,' ');if(next===out)break;out=next;}return out;}
function balancedObject(text:string,start:number){let depth=0,inString=false,escape=false;for(let i=start;i<text.length;i++){const ch=text[i];if(inString){if(escape){escape=false;continue;}if(ch==='\\'){escape=true;continue;}if(ch==='"')inString=false;continue;}if(ch==='"'){inString=true;continue;}if(ch==='{')depth++;else if(ch==='}'){depth--;if(depth===0)return text.slice(start,i+1);}}return null;}
function extractProducts(html:string){const text=decode(html),objects:any[]=[],seen=new Set<string>();let cursor=0;while(true){const marker=text.indexOf('"wssId"',cursor);if(marker<0)break;cursor=marker+7;let start=text.lastIndexOf('{"id"',marker);if(start<0||marker-start>1200)continue;const candidate=balancedObject(text,start);if(!candidate)continue;try{const obj=JSON.parse(candidate);const id=String(obj.wssId||obj.id||'').trim(),title=String(obj.title||'').trim();if(!id||!title||!obj.price||!obj.campaignInfo||seen.has(id))continue;seen.add(id);objects.push(obj);}catch{/* skip malformed embedded fragment */}}
 return objects;}
function numberFromPrice(value:unknown){if(typeof value==='number'&&Number.isFinite(value))return value;const m=String(value??'').replace(/\u00a0/g,' ').match(/(\d+(?:[.,]\d+)?)/u);return m?Number(m[1].replace(',','.')):null;}
function dateOnly(value:unknown){const m=String(value??'').match(/(\d{4})[\/-](\d{2})[\/-](\d{2})/u);return m?`${m[1]}-${m[2]}-${m[3]}`:null;}
function compact(obj:any){const price=obj.price||{},campaign=obj.campaignInfo||{};return{id:String(obj.id||''),wssId:String(obj.wssId||''),title:String(obj.title||''),url:String(obj.link||obj.url||''),price:numberFromPrice(price.minSinglePrice??price.value??price.text??price.additionalInfo?.value),old_price:numberFromPrice(price.beforePricePrimary??price.beforePriceSecondary??price.beforePrice),discount:Number(price.discount||0)||null,image:String(obj.image||''),valid_from:dateOnly(campaign.campaignPriceStartDate),valid_to:dateOnly(campaign.campaignPriceEndDate),campaign:Boolean(obj.campaign),specialSale:Boolean(obj.specialSale),whileStockLasts:Boolean(obj.whileStockLasts),statusCode:String(obj.statusCode||'')};}

Deno.serve(async request=>{if(request.method==='OPTIONS')return new Response('ok',{headers:CORS});if(request.method!=='POST')return json({error:'Method not allowed'},405);if(!(await allowed(request)))return json({error:'Unauthorized'},401);try{const body=await request.json().catch(()=>({}));if(body.dry_run!==true)return json({error:'JYSK produktová publikace zatím není povolena; použij dry_run.'},409);const[campaign,sale]=await Promise.all([fetchText(SOURCE),fetchText(SALE)]);const products=extractProducts(sale.text).map(compact);const today=new Date().toISOString().slice(0,10);const current=products.filter(p=>p.price&&p.price>0&&p.valid_to&&p.valid_to>=today&&p.valid_from&&p.valid_from<=today);const publications=[...new Set([...campaign.text.matchAll(/https:\/\/ipaper\.ipapercms\.dk\/jysk\/cz\/CampaignPaper\/[a-z0-9_]+/gi)].map(x=>x[0]))];return json({ok:true,dry_run:true,source:sale.url,html_bytes:sale.text.length,embedded_products:products.length,current_products:current.length,publications,validity_ranges:[...new Set(current.map(p=>`${p.valid_from}..${p.valid_to}`))].sort(),samples:current.slice(0,120),all_samples:products.slice(0,30)});}catch(error){return json({error:error instanceof Error?error.message:String(error),code:'JYSK_PRODUCT_DRY_RUN_FAILED'},500)}});
