import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const URL=Deno.env.get('SUPABASE_URL')!,KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,CRON=Deno.env.get('CRON_SECRET')||'';
const db=createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const API='https://api.hm.com/search-services/v1/cs_cz/listing/resultpage',SHOP='https://www2.hm.com',ADAPTER='hm-official-api-sale-v1';
const ROOTS=['ladies','men','kids','home'],PAGE_SIZE=72,MAX_PAGES=120,MAX_PRODUCTS=10000,MAX_MS=75000,CONCURRENCY=8;
const H={'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','access-control-allow-headers':'authorization,apikey,content-type,x-cron-secret','access-control-allow-methods':'POST,OPTIONS'};
const json=(v:unknown,s=200)=>new Response(JSON.stringify(v),{status:s,headers:H});
function err(e:unknown){if(e instanceof Error)return e.message;if(e&&typeof e==='object'){const x=e as Record<string,unknown>;return [x.message,x.details,x.hint,x.code].filter(Boolean).map(String).join(' | ')||JSON.stringify(e)}return String(e)}
async function allowed(r:Request){const t=(r.headers.get('authorization')||'').replace(/^Bearer\s+/i,'').trim();if(t===KEY||(CRON&&r.headers.get('x-cron-secret')===CRON))return true;if(!t)return false;const {data,error}=await db.auth.getUser(t);return !error&&!!data.user&&['admin','editor'].includes(String(data.user?.app_metadata?.role||'').toLowerCase())}
function norm(v:string){return v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('cs').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim()}
function today(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Prague',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),x=Object.fromEntries(p.map(y=>[y.type,y.value]));return `${x.year}-${x.month}-${x.day}`}
function plusDay(v:string){const d=new Date(`${v}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+1);return d.toISOString().slice(0,10)}
async function hash(v:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function endpoint(root:string,page:number){const p=new URLSearchParams({categoryId:root,page:String(page),pageSize:String(PAGE_SIZE),sort:'RELEVANCE',touchPoint:'DESKTOP',pageId:root,filters:'sale:true'});return `${API}?${p}`}
async function fetchPage(root:string,page:number){const c=new AbortController(),timer=setTimeout(()=>c.abort(),15000);try{const r=await fetch(endpoint(root,page),{headers:{'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/151 Safari/537.36',accept:'application/json','accept-language':'cs-CZ,cs;q=0.9'},redirect:'follow',signal:c.signal});const text=await r.text();if(!r.ok)throw new Error(`H&M API ${root}/${page} HTTP ${r.status}: ${text.slice(0,250)}`);const data=JSON.parse(text);if(!data?.plpList)throw new Error(`H&M API ${root}/${page} vrátilo neočekávaný formát.`);return data}finally{clearTimeout(timer)}}
function price(p:any,type:string){const v=p?.prices?.find((x:any)=>x?.priceType===type)?.price;return typeof v==='number'&&Number.isFinite(v)&&v>0?v:null}
function row(p:any,root:string,d:string){const id=String(p?.id||'').trim(),title=String(p?.productName||'').replace(/\s+/g,' ').trim(),sale=price(p,'redPrice'),white=price(p,'whitePrice');if(!/^\d{8,14}$/.test(id)||!title||!sale)return null;if(p?.availability?.stockState&&p.availability.stockState!=='Available')return null;const rel=String(p?.url||'').trim(),source=rel.startsWith('http')?rel:new globalThis.URL(rel||`/cs_cz/productpage.${id}.html`,SHOP).toString(),image=String(p?.productImage||p?.modelImage||'').trim(),old=white&&white>sale?white:null;return {external_id:`hm:${id}`,title,normalized_title:norm(title),price:sale,old_price:old,valid_from:d,valid_to:plusDay(d),source_url:source,image_url:/^https:\/\/image\.hm\.com\//i.test(image)?image:null,quantity_text:null,confidence:0.99,metadata:{adapter:ADAPTER,hm_product_id:id,category_root:root,brand:p?.brandName||'H&M',color:p?.colorName||null,external_brand:p?.external===true,availability:p?.availability?.stockState||null,price_policy:'official_red_price',reference_price_policy:old?'official_white_price':'none',validity_policy:'daily_verified_snapshot_plus_one_day'}}}
async function collect(){const started=Date.now(),first=await Promise.all(ROOTS.map(async root=>({root,data:await fetchPage(root,1)}))),counts=new Map<string,number>(),all:Array<{root:string,p:any}>=[];for(const {root,data} of first){const hits=Number(data?.plpList?.numberOfHits||0),pages=Math.max(hits>0?1:0,Number(data?.pagination?.totalPages||0));counts.set(root,pages);for(const p of data?.plpList?.productList||[])all.push({root,p})}const total=[...counts.values()].reduce((a,b)=>a+b,0);if(total>MAX_PAGES)throw new Error(`H&M výprodej má ${total} API stran; bezpečný limit je ${MAX_PAGES}. Předchozí data zůstala beze změny.`);const pending:Array<{root:string,page:number}>=[];for(const [root,pages] of counts)for(let page=2;page<=pages;page++)pending.push({root,page});for(let i=0;i<pending.length;i+=CONCURRENCY){if(Date.now()-started>MAX_MS)throw new Error('H&M API sync překročil bezpečný časový limit před dokončením celé sady; nic nebylo publikováno.');const batch=await Promise.all(pending.slice(i,i+CONCURRENCY).map(async x=>({root:x.root,data:await fetchPage(x.root,x.page)})));for(const {root,data} of batch)for(const p of data?.plpList?.productList||[])all.push({root,p})}const d=today(),byId=new Map<string,any>();for(const x of all){const r=row(x.p,x.root,d);if(r)byId.set(r.external_id,r)}const rows=[...byId.values()].sort((a,b)=>a.external_id.localeCompare(b.external_id));if(rows.length>MAX_PRODUCTS)throw new Error(`H&M API vrátilo ${rows.length} unikátních zlevněných položek; limit je ${MAX_PRODUCTS}. Nic nebylo publikováno.`);return {rows,pageCounts:Object.fromEntries(counts),totalPages:total,raw:all.length,duration:Date.now()-started}}
async function activate(storeId:string){const {data:s,error}=await db.from('leaflet_sources').select('id').eq('store_id',storeId).eq('name','H&M – oficiální výprodej').limit(1).maybeSingle();if(error)throw error;if(!s)throw new Error('H&M zdroj nebyl nalezen.');const {error:u}=await db.from('leaflet_sources').update({source_url:API,source_type:'api',is_active:true,auto_publish:true,check_interval_minutes:120,automation_mode:'automatic',adapter_key:ADAPTER,extraction_strategy:'structured_api',disabled_reason:null,next_review_at:null,last_checked_at:new Date().toISOString(),last_error:null,last_strategy_used:'official_structured_api'}).eq('id',s.id);if(u)throw u;return String(s.id)}
async function markWaiting(storeId:string,sourceId:string){const now=new Date().toISOString(),reason='Oficiální H&M API je dostupné; český katalog aktuálně nevrací žádné aktivní výprodejové položky.';const {error:e}=await db.from('store_product_sync_state').update({last_run_at:now,last_success_at:now,last_error:null,last_parser_error:null,health_status:'waiting_source',health_reason:reason,last_offer_count:0,expected_offer_count:0,last_published_count:0,source_type:'official-api',source_category:'sale',parser_version:ADAPTER,adapter_name:ADAPTER,adapter_version:ADAPTER,is_running:false,run_started_at:null,updated_at:now}).eq('store_id',storeId);if(e)throw e;const {error:s}=await db.from('leaflet_sources').update({last_checked_at:now,last_success_at:now,last_error:null,last_strategy_used:'official_structured_api',last_strategy_success_at:now}).eq('id',sourceId);if(s)throw s;return reason}
Deno.serve(async request=>{if(request.method==='OPTIONS')return new Response('ok',{headers:H});if(request.method!=='POST')return json({error:'Method not allowed'},405);if(!(await allowed(request)))return json({error:'Unauthorized'},401);let storeId:string|null=null,sourceId:string|null=null;try{const body=await request.json().catch(()=>({}));const {data:store,error:se}=await db.from('stores').select('id,name').eq('slug','hm').single();if(se||!store)throw se||new Error('H&M obchod nebyl nalezen.');storeId=String(store.id);const c=await collect();if(body.dry_run===true)return json({ok:true,dry_run:true,store:'H&M',publishable:c.rows.length,raw_products:c.raw,total_pages:c.totalPages,pages_by_root:c.pageCounts,duration_ms:c.duration,samples:c.rows.slice(0,10)});sourceId=await activate(storeId);if(c.rows.length===0){const reason=await markWaiting(storeId,sourceId);return json({ok:true,no_changes:true,no_active_sale:true,store:'H&M',publishable:0,total_pages:c.totalPages,pages_by_root:c.pageCounts,duration_ms:c.duration,reason})}const signature=await hash(c.rows.map((r:any)=>[r.external_id,r.price,r.old_price||'',r.valid_from,r.valid_to,r.source_url].join('|')).join('\n'));const {data:result,error}=await db.rpc('publish_structured_store_offers',{p_store_slug:'hm',p_adapter:ADAPTER,p_signature:signature,p_rows:c.rows,p_min_products:1,p_max_products:MAX_PRODUCTS,p_source_document_url:API,p_parser_version:ADAPTER});if(error)throw error;return json({ok:true,self_published:true,store:'H&M',published:c.rows.length,with_reference_price:c.rows.filter((r:any)=>r.old_price&&r.old_price>r.price).length,total_pages:c.totalPages,pages_by_root:c.pageCounts,duration_ms:c.duration,signature,result})}catch(e){const message=err(e),now=new Date().toISOString();if(storeId)await db.from('store_product_sync_state').update({last_run_at:now,last_error:message.slice(0,2000),last_parser_error:message.slice(0,2000),health_status:'error',health_reason:'H&M oficiální API sync nebyl dokončen; předchozí veřejná data zůstala beze změny.',is_running:false,run_started_at:null,updated_at:now}).eq('store_id',storeId);if(sourceId)await db.from('leaflet_sources').update({last_checked_at:now,last_error:message.slice(0,1000)}).eq('id',sourceId);return json({error:message,code:'HM_PRODUCT_SYNC_FAILED'},500)}});
