import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const URL=Deno.env.get('SUPABASE_URL')!,KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,CRON=Deno.env.get('CRON_SECRET')||'';
const db=createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}}),SOURCE='https://www.rohlik.cz/cs-CZ/cenove-trhaky',ADAPTER='rohlik-price-hits-html-v1',PARSER='rohlik-price-hits-html-v2';
const H={'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','access-control-allow-headers':'authorization,apikey,content-type,x-cron-secret'};
const json=(v:unknown,s=200)=>new Response(JSON.stringify(v),{status:s,headers:H}),allowed=(r:Request)=>r.headers.get('authorization')===`Bearer ${KEY}`||Boolean(CRON&&r.headers.get('x-cron-secret')===CRON);
function today(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Prague',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),x=Object.fromEntries(p.map(y=>[y.type,y.value]));return `${x.year}-${x.month}-${x.day}`;}
function plus(v:string){const d=new Date(`${v}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+1);return d.toISOString().slice(0,10)}
function clean(v:string){return v.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#x27;/g,"'").replace(/&nbsp;/g,' ').trim()}
function num(v:string){const n=Number(v.replace(/[^0-9,.-]/g,'').replace(',','.'));return Number.isFinite(n)?n:null}
async function hash(v:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:H});if(req.method!=='POST')return json({error:'Method not allowed'},405);if(!allowed(req))return json({error:'Unauthorized'},401);try{
 const res=await fetch(SOURCE,{headers:{'user-agent':'Mozilla/5.0','accept':'text/html,application/xhtml+xml','accept-language':'cs-CZ,cs;q=0.9'},redirect:'follow'});if(!res.ok)throw new Error(`Rohlík HTTP ${res.status}`);const html=await res.text(),d=today(),to=plus(d),rows:any[]=[];
 for(const block of html.split('data-test="productCard-AVAILABLE-').slice(1)){const pid=block.match(/^([0-9]+)/)?.[1]||'',price=Number(block.match(/<meta content="([0-9.]+)" itemprop="price">/)?.[1]||'NaN'),old=num(block.match(/data-test="productCard-body-price-sale">([^<]+)<\/span>/)?.[1]||''),titleRaw=block.match(/data-test="productCard-body-name" title="([^"]+)"/)?.[1]||'',href=block.match(/href="(\/[0-9]+-[^"]+)"/)?.[1]||'',image=block.match(/data-test="productCard-header-image-img" src="([^"]+)"/)?.[1]||'',amount=clean(block.match(/data-test="productCard-footer-amount">([^<]+)<\/p>/)?.[1]||'');if(!/^\d+$/.test(pid)||!Number.isFinite(price)||!old||old<=price||!titleRaw||!href||!image)continue;const title=clean(titleRaw),discount=Math.round((1-price/old)*100);if(title.length<3||price<2||price>100000||old>200000||discount<1||discount>95)continue;rows.push({external_id:`rohlik:${pid}`,title,normalized_title:title.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim(),price,old_price:old,valid_from:d,valid_to:to,source_url:`https://www.rohlik.cz${href}`,image_url:image,confidence:0.99,metadata:{adapter:ADAPTER,parser_version:PARSER,rohlik_product_id:pid,amount:amount||null,discount_percent:discount,price_policy:'current_and_crossed_price_from_official_price_hits',validity_policy:'daily_snapshot_plus_one_day'}})}
 const unique=[...new Map(rows.map(r=>[r.external_id,r])).values()];if(unique.length<20||unique.length>300)throw new Error(`Rohlík safe product count ${unique.length} outside 20-300`);unique.sort((a,b)=>a.external_id.localeCompare(b.external_id));const signature=await hash(`${d}\n${unique.map(r=>`${r.external_id}|${r.price}|${r.old_price}`).join('\n')}`);const {data:result,error}=await db.rpc('publish_structured_store_offers',{p_store_slug:'rohlik',p_adapter:ADAPTER,p_signature:signature,p_rows:unique,p_min_products:20,p_max_products:300,p_source_document_url:SOURCE,p_parser_version:PARSER});if(error)throw new Error(error.message||JSON.stringify(error));return json({ok:true,published:unique.length,date:d,valid_to:to,signature,result});
 }catch(e){return json({error:e instanceof Error?e.message:String(e),code:'ROHLIK_PRICE_HITS_V2_FAILED'},500)}});
