import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=Deno.env.get('SUPABASE_URL')!, K=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!, C=Deno.env.get('CRON_SECRET')||'';
const H={'content-type':'application/json; charset=utf-8'};const J=(v:unknown,s=200)=>new Response(JSON.stringify(v),{status:s,headers:H});
const auth=(r:Request)=>r.headers.get('authorization')===`Bearer ${K}`||Boolean(C&&r.headers.get('x-cron-secret')===C);
const cl=(s:string)=>String(s||'').replace(/\s+/g,' ').trim();
function norm(s:string){return cl(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,' ').trim();}
const STOP=new Set('A I V S Z NA DO OD ZA PRO PRI SE JE JSOU BAL BALENI CENA KUS KS CHLAZ CHLAZENE MRAZ MRAZENE VAZ VAZENE VICE VSECHNY VYBRANE DRUHY DRUH MIX CCA ML KG G L PROCENT ORIGINAL'.split(' '));
const GENERIC=new Set('PIVO VODA JOGURT SAMPON DEODORANT CISTICI PROSTREDEK PRACI PRASEK TYČINKA TYCINKA TYČINKY TYCINKY OPLATKY CHIPSY SALAM SUNKA SUNKY TESTOVINY KAPESNIKY MLEKO MAJONEZA OMACKA KAVA NAPOJ COKOLADA PECIVO CHLEB BRAMBORY SARDINKY RAJCATA KRUPICKA TVAROH KNEDLIK PASTIKA SYR SÝR MASLO MASLOVA OLEJ CUKR MOUKA RYZE RYZE TEKUTE PRADLO NADOBI VLASY PANSKY PANSKE DAMSKY DÁMSKÝ'.split(' '));
function terms(s:string){return [...new Set(norm(s).split(' ').filter(x=>x.length>=3&&!STOP.has(x)&&!/^\d+$/.test(x)))];}
type M={dim:'mass'|'volume',value:number};
function measures(s:string):M[]{const out:M[]=[];for(const m of s.matchAll(/(\d+(?:[,.]\d+)?)\s*(kg|g|ml|l)\b/gi)){const n=Number(m[1].replace(',','.'));const u=m[2].toLowerCase();if(!Number.isFinite(n))continue;if(u==='kg')out.push({dim:'mass',value:n*1000});else if(u==='g')out.push({dim:'mass',value:n});else if(u==='l')out.push({dim:'volume',value:n*1000});else out.push({dim:'volume',value:n});}return out;}
function packageCheck(title:string,quantity:any[]):{ok:boolean,titleMeasures:M[],balMeasures:M[],bestDiff:number|null,tolerance:number}{const bal=(Array.isArray(quantity)?quantity:[]).filter(x=>/bal\.:/i.test(String(x))).join(' ');const a=measures(title),b=measures(bal);const tol=/\bcca\b/i.test(title+' '+bal)?0.12:0.05;let best=Infinity,comparable=false;for(const x of a)for(const y of b)if(x.dim===y.dim){comparable=true;const d=Math.abs(x.value-y.value)/Math.max(x.value,y.value);if(d<best)best=d;}return {ok:!comparable||best<=tol,titleMeasures:a,balMeasures:b,bestDiff:comparable?+best.toFixed(4):null,tolerance:tol};}
function identityCheck(title:string,brand:string,titleMatch:string){const bt=new Set(terms(brand)),tt=terms(title),mt=new Set(terms(titleMatch));const specific=tt.filter(x=>!bt.has(x)&&!GENERIC.has(x));const matched=specific.filter(x=>mt.has(x));return {ok:specific.length===0||matched.length>0,specific,matched,brand_terms:[...bt],match_terms:[...mt]};}
Deno.serve(async req=>{if(req.method!=='POST')return J({error:'method'},405);if(!auth(req))return J({error:'auth'},401);try{const body=await req.json().catch(()=>({}));const r=await fetch(`${U}/functions/v1/debug-makro-full-dryrun`,{method:'POST',headers:{authorization:`Bearer ${K}`,apikey:K,'content-type':'application/json'},body:JSON.stringify(body)});const text=await r.text();if(!r.ok)return J({error:`base_dryrun_http_${r.status}`,detail:text.slice(0,1000)},502);const d=JSON.parse(text);const safe:any[]=[],extraRejected:any[]=[];for(const x of d.verified||[]){const pkg=packageCheck(String(x.title||''),x.quantity||[]);if(!pkg.ok){extraRejected.push({...x,reason:'packaging_mismatch',guard:{package:pkg}});continue;}const ident=identityCheck(String(x.title||''),String(x.brand||''),String(x.title_match||''));if(!ident.ok){extraRejected.push({...x,reason:'non_specific_title_match',guard:{identity:ident,package:pkg}});continue;}safe.push({...x,guard:{identity:ident,package:pkg}});}const counts:any={...(d.rejected_by_reason||{})};for(const x of extraRejected)counts[x.reason]=(counts[x.reason]||0)+1;return J({ok:true,base_total:d.total_codes,base_verified:d.verified_count,base_rejected:d.rejected_count,final_safe_count:safe.length,final_rejected_count:(d.rejected?.length||0)+extraRejected.length,rejected_by_reason:counts,added_rejections:extraRejected.length,safe,extra_rejected:extraRejected,base_rejected_items:d.rejected||[],duration_ms:d.duration_ms});}catch(e){return J({error:e instanceof Error?e.message:String(e)},500)}});
