import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!,KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,CRON=Deno.env.get('CRON_SECRET')||'';
const db=createClient(SUPABASE_URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const GROUP='makro-letaky-a-katalogy',LIST=`https://api.publitas.com/v1/groups/${GROUP}/publications.json`,VIEW='https://letaky.makro.cz',ASSET='https://view.publitas.com',ADAPTER='makro-publitas-source-v1';
const CORS={'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','access-control-allow-headers':'authorization,apikey,content-type,x-cron-secret','access-control-allow-methods':'POST,OPTIONS'};
const HEAD={'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/151 Safari/537.36',accept:'application/json,text/html,application/pdf,*/*;q=0.8','accept-language':'cs-CZ,cs;q=0.9'};
const json=(v:unknown,s=200)=>new Response(JSON.stringify(v),{status:s,headers:CORS});
function msg(e:unknown){return e instanceof Error?e.message:String(e)}
async function allowed(r:Request){const t=(r.headers.get('authorization')||'').replace(/^Bearer\s+/i,'').trim();if(t===KEY||(CRON&&r.headers.get('x-cron-secret')===CRON))return true;if(!t)return false;const{data,error}=await db.auth.getUser(t);return !error&&!!data.user&&['admin','editor'].includes(String(data.user?.app_metadata?.role||'').toLowerCase())}
async function text(url:string,timeout=25000){const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{headers:HEAD,redirect:'follow',signal:c.signal});const body=await r.text();if(!r.ok)throw new Error(`${new globalThis.URL(url).hostname} HTTP ${r.status}`);return body}finally{clearTimeout(timer)}}
function viewerData(html:string){const m='var data =',a=html.indexOf(m),b=html.indexOf('{',a+m.length),c=html.indexOf('Reader.Bootstrap.init',b);if(a<0||b<0||c<0)throw new Error('MAKRO Publitas viewer má neočekávaný formát.');const block=html.slice(b,c),semi=block.lastIndexOf(';');return JSON.parse((semi>=0?block.slice(0,semi):block).trim())}
function dates(input:string){const m=input.match(/(\d{1,2})\.\s*(\d{1,2})\.\s*[–-]\s*(\d{1,2})\.\s*(\d{1,2})\.\s*(\d{4})/u);if(!m)return {from:null,to:null};const sm=Number(m[2]),em=Number(m[4]),ey=Number(m[5]),sy=sm>em?ey-1:ey;const iso=(y:number,mo:string,d:string)=>`${y}-${mo.padStart(2,'0')}-${d.padStart(2,'0')}`;return {from:iso(sy,m[2],m[1]),to:iso(ey,m[4],m[3])}}
function pdfUrl(raw:string){const u=new globalThis.URL(raw,ASSET);if(u.protocol!=='https:'||u.hostname!=='view.publitas.com'||!/^\/11102\/\d+\/pdfs\/[a-f0-9-]+\.pdf$/iu.test(u.pathname))throw new Error('MAKRO vrátilo neočekávanou PDF adresu.');return u.toString()}
async function probe(url:string){const r=await fetch(url,{headers:{...HEAD,accept:'application/pdf,*/*;q=0.8',range:'bytes=0-7'},redirect:'follow'});if(!r.ok&&r.status!==206)throw new Error(`MAKRO PDF HTTP ${r.status}.`);const b=new Uint8Array(await r.arrayBuffer());if(b.length<4||b[0]!==37||b[1]!==80||b[2]!==68||b[3]!==70)throw new Error('MAKRO místo PDF vrátilo jiný obsah.')}
async function hash(v:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function pragueDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Prague',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
Deno.serve(async r=>{if(r.method==='OPTIONS')return new Response('ok',{headers:CORS});if(r.method!=='POST')return json({error:'Method not allowed'},405);if(!(await allowed(r)))return json({error:'Unauthorized'},401);const now=new Date().toISOString();let storeId:string|null=null,sourceId:string|null=null;try{const{data:store,error:se}=await db.from('stores').select('id,name').eq('slug','makro').single();if(se||!store)throw se||new Error('MAKRO obchod nebyl nalezen.');storeId=String(store.id);const{data:source,error:ss}=await db.from('leaflet_sources').select('id').eq('store_id',store.id).eq('name','MAKRO – aktuální nabídky').limit(1).single();if(ss||!source)throw ss||new Error('MAKRO zdroj nebyl nalezen.');sourceId=String(source.id);
const pubs=JSON.parse(await text(LIST));if(!Array.isArray(pubs))throw new Error('MAKRO Publitas API nevrátilo seznam publikací.');const retail=pubs.filter((p:any)=>String(p?.title||'').trim().toLocaleLowerCase('cs')==='maloobchod'&&!String(p?.slug||'').includes('distribuce')).sort((a:any,b:any)=>Date.parse(String(b.onlineAt||0))-Date.parse(String(a.onlineAt||0)))[0];if(!retail?.slug||!retail?.id)throw new Error('MAKRO nemá nalezený aktuální maloobchodní leták.');const slug=String(retail.slug);if(!/^maloobchod-[a-z0-9_-]+$/i.test(slug))throw new Error(`Neočekávaný MAKRO slug: ${slug}`);const viewer=`${VIEW}/${slug}/`,html=await text(viewer),vd=viewerData(html);if(Number(vd.id)!==Number(retail.id))throw new Error('MAKRO publication ID se neshoduje mezi API a viewerem.');const token=String(vd.cacheToken||'');if(!token)throw new Error('MAKRO viewer nevrátil cacheToken.');const spreads=JSON.parse(await text(`${viewer}spreads.json?version=${encodeURIComponent(token)}`));if(!Array.isArray(spreads)||!spreads.length)throw new Error('MAKRO viewer nevrátil stránky.');const pages=spreads.flatMap((s:any)=>Array.isArray(s?.pages)?s.pages:[]),pageCount=pages.length;if(pageCount<4||pageCount>100)throw new Error(`Podezřelý počet stran MAKRO: ${pageCount}`);const joined=pages.slice(0,3).map((p:any)=>String(p?.text||'')).join('\n'),valid=dates(joined);if(!valid.from||!valid.to)throw new Error('MAKRO leták nemá rozpoznatelnou platnost.');const rawPdf=String(vd.config?.downloadPdfUrl||'');if(!rawPdf)throw new Error('MAKRO viewer nevrátil PDF.');const pdf=pdfUrl(rawPdf);await probe(pdf);const sourceHash=await hash(`${source.id}|${retail.id}|${slug}|${ADAPTER}`),metadata={adapter:ADAPTER,title:'MAKRO – Maloobchod',publication_id:Number(retail.id),publication_slug:slug,publitas_group:GROUP,online_at:retail.onlineAt||null,page_count:pageCount,viewer_url:viewer,cache_token:token,source_page:LIST,last_seen_at:now,validity_policy:'explicit_flyer_date_range',price_policy:'gross_price_parser_validated_with_exact_catalog_identity'};
const{data:existing,error:ee}=await db.from('leaflet_imports').select('id,metadata,product_count').eq('source_hash',sourceHash).maybeSingle();if(ee)throw ee;let importId:string;if(existing){importId=String(existing.id);const{error}=await db.from('leaflet_imports').update({source_document_url:pdf,status:'published',confidence:0.99,coverage_scope:'national',detected_valid_from:valid.from,detected_valid_to:valid.to,finished_at:now,error_message:null,metadata:{...(existing.metadata||{}),...metadata},updated_at:now}).eq('id',existing.id);if(error)throw error}else{const{data:created,error}=await db.from('leaflet_imports').insert({source_id:source.id,store_id:store.id,source_document_url:pdf,source_hash:sourceHash,status:'published',product_count:0,confidence:0.99,coverage_scope:'national',detected_valid_from:valid.from,detected_valid_to:valid.to,finished_at:now,metadata}).select('id').single();if(error||!created)throw error||new Error('MAKRO import se nepodařilo uložit.');importId=String(created.id)}
await db.from('leaflet_imports').update({status:'ignored',updated_at:now}).eq('source_id',source.id).neq('id',importId).in('status',['published','review','publishing']).contains('metadata',{adapter:ADAPTER});await db.from('leaflet_sources').update({source_url:LIST,source_type:'api',is_active:true,auto_publish:true,check_interval_minutes:60,automation_mode:'specialized',adapter_key:ADAPTER,extraction_strategy:'structured_publitas',disabled_reason:null,next_review_at:null,last_checked_at:now,last_success_at:now,last_error:null,last_strategy_used:'official_publitas_api',last_strategy_success_at:now}).eq('id',source.id);
const today=pragueDate();const{count:offerCount,error:oe}=await db.from('offers').select('id',{count:'exact',head:true}).eq('store_id',store.id).eq('status','published').lte('valid_from',today).gte('valid_to',today);if(oe)throw oe;const currentOffers=Number(offerCount||0),healthy=currentOffers>0;await db.from('store_product_sync_state').update({health_status:healthy?'ok':'degraded',health_reason:healthy?`MAKRO: oficiální maloobchodní leták ${valid.from}–${valid.to} ověřen; aktuálně je zveřejněno ${currentOffers} katalogově ověřených produktů s cenou s DPH.`:`MAKRO: oficiální maloobchodní leták ${valid.from}–${valid.to} je dostupný; produktový sync zatím nemá bezpečně ověřené veřejné nabídky.`,last_error:null,last_parser_error:null,last_run_at:now,last_success_at:now,source_type:healthy?'official-publitas+catalog':'official-publitas',source_category:'maloobchod',is_running:false,updated_at:now}).eq('store_id',store.id);return json({ok:true,store:store.name,import_id:importId,publication_id:Number(retail.id),publication_slug:slug,viewer_url:viewer,pdf_url:pdf,page_count:pageCount,valid_from:valid.from,valid_to:valid.to,current_offers:currentOffers,adapter:ADAPTER})}catch(e){const m=msg(e);if(sourceId)await db.from('leaflet_sources').update({last_checked_at:now,last_error:m.slice(0,1000)}).eq('id',sourceId);if(storeId)await db.from('store_product_sync_state').update({last_run_at:now,last_error:m.slice(0,2000),health_status:'error',health_reason:'MAKRO oficiální Publitas zdroj se nepodařilo ověřit; předchozí veřejná data zůstala beze změny.',is_running:false,updated_at:now}).eq('store_id',storeId);return json({error:m,code:'MAKRO_SOURCE_SYNC_FAILED'},500)}});
