import * as pdfjs from 'npm:pdfjs-dist@4.10.38/legacy/build/pdf.mjs';
const SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,CRON=Deno.env.get('CRON_SECRET')||'';
const LANDING='https://www.itesco.cz/akcni-nabidky/letaky-a-katalogy';
const H={'user-agent':'Mozilla/5.0 Chrome/151 Safari/537.36',accept:'text/html,application/pdf,*/*','accept-language':'cs-CZ,cs;q=0.9'};
const clean=(v:any)=>String(v??'').replace(/\s+/g,' ').trim(),norm=(v:any)=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim(),ref=(v:any)=>clean(v?.__ref);
const STOP=new Set(['tesco','vybrane','vybrany','druhy','druh','cena','balene','baleny','balena','volny','prodej','clubcard','vice','kus','kusy','baleni','nabidka','nabidky','bez','pro','sada','mix']);
const allowed=(r:Request)=>r.headers.get('authorization')===`Bearer ${SERVICE}`||Boolean(CRON&&r.headers.get('x-cron-secret')===CRON),resp=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json; charset=utf-8'}});
function nextData(h:string){const a=h.indexOf('<script id="__NEXT_DATA__"'),b=h.indexOf('>',a),c=h.indexOf('</script>',b+1);if(a<0||b<0||c<0)throw Error('NEXT_DATA');return JSON.parse(h.slice(b+1,c));}
async function text(u:string){const r=await fetch(u,{headers:H,redirect:'follow',signal:AbortSignal.timeout(30000)}),t=await r.text();if(!r.ok)throw Error(`HTTP ${r.status}`);return t;}
async function viewer(){const h=await text(`${LANDING}?x=${Date.now()}`),m=h.match(/href=["']([^"']*\/hypermarkety\/tesco-letak-\d{4}-\d{2}-\d{2}\/1)["']/i);if(!m)throw Error('viewer');return new URL(m[1],LANDING).toString();}
function explicitViewer(value:any){const raw=clean(value);if(!raw)return null;let u:URL;try{u=new URL(raw);}catch{throw Error('viewer_url');}if(u.protocol!=='https:'||u.hostname!=='www.itesco.cz'||!/^\/akcni-nabidky\/letaky-a-katalogy\/hypermarkety\/tesco-letak-\d{4}-\d{2}-\d{2}\/1\/?$/i.test(u.pathname))throw Error('viewer_url');u.search='';u.hash='';return u.toString();}
function apollo(h:string){const nd=nextData(h),pp=nd?.props?.pageProps||{},s=pp.__APOLLO_STATE__||{},ls=Object.values(s).filter((v:any)=>v?.__typename==='Leaflet'&&v?.type==='HM'&&Array.isArray(v.pages)).sort((a:any,b:any)=>String(b.validFrom||'').localeCompare(String(a.validFrom||'')))as any[],l=ls[0];if(!l)throw Error('leaflet');const pages=l.pages.map(ref).filter(Boolean).map((r:string)=>({ref:r,...s[r]})).filter((p:any)=>p.__typename==='LeafletMetadataPage');return{s,l,pages,pdf:clean(l.leafletUrl),endpoint:clean(pp?.config?.APOLLO_URL),country:clean(pp?.region||pp?.config?.region||'cz')};}
const LEAFLET_PAGES_QUERY=`
query getLeafletPages($country: CountryCode!, $slug: String!, $leafletType: LeafletType, $storeId: String) {
  leafletBySlug(country: $country, slug: $slug, leafletType: $leafletType, storeId: $storeId) {
    ...CustomerLeafletItem
  }
}
fragment CustomerProductByPositionItem on LeafletProduct {
  id
  promoOfferName
  isMainProduct
  addToBasketURL
  addToShareURL
  product {
    isInGhs
    pngFileURL
    productName
    productPeriods { id periodName promoStart promoEnd }
  }
}
fragment CustomerPagePositionItem on LeafletMetadataPagePosition {
  id
  calculatedPositionX
  calculatedPositionY
  type
  hyperlinkUrl
  width
  height
  products { ...CustomerProductByPositionItem }
}
fragment CustomerLeafletPageItem on LeafletMetadataPage {
  id
  page
  pagePNG
  positions { ...CustomerPagePositionItem }
}
fragment CustomerLeafletItem on Leaflet {
  id
  type
  leafletUrl
  pages { ...CustomerLeafletPageItem }
  validFrom
  validTo
}`;
function traceparent(){const a=crypto.getRandomValues(new Uint8Array(16)),b=crypto.getRandomValues(new Uint8Array(8)),hex=(x:Uint8Array)=>[...x].map(v=>v.toString(16).padStart(2,'0')).join('');return `00-${hex(a)}-${hex(b)}-01`;}
async function publicPages(a:any,v:string){if(!/^https:\/\/api\.prod\.retail\.tesco\.com\/marketing\/leaflets-be\/graphql$/i.test(a.endpoint))throw Error('tesco_public_graphql_endpoint');const slug=v.match(/\/(tesco-letak-\d{4}-\d{2}-\d{2})\/1\/?$/i)?.[1];if(!slug)throw Error('tesco_viewer_slug');const variables={country:a.country||'cz',slug,leafletType:'HM',storeId:null};const r=await fetch(a.endpoint,{method:'POST',headers:{'user-agent':H['user-agent'],'accept-language':H['accept-language'],accept:'application/json','content-type':'application/json',origin:'https://www.itesco.cz',referer:v,traceparent:traceparent()},body:JSON.stringify({operationName:'getLeafletPages',variables,query:LEAFLET_PAGES_QUERY}),signal:AbortSignal.timeout(30000)}),body=await r.text();let payload:any=null;try{payload=JSON.parse(body);}catch{}if(!r.ok||payload?.errors?.length||!payload?.data?.leafletBySlug)throw Error(`tesco_public_graphql HTTP ${r.status}: ${body.slice(0,600)}`);const l=payload.data.leafletBySlug,pages=Array.isArray(l.pages)?l.pages:[];if(Number(l.id)!==Number(a.l.id)||clean(l.type)!==clean(a.l.type)||clean(l.leafletUrl)!==a.pdf||clean(l.validFrom)!==clean(a.l.validFrom)||clean(l.validTo)!==clean(a.l.validTo))throw Error('tesco_public_graphql_snapshot_mismatch');if(pages.length!==a.pages.length)throw Error(`tesco_public_graphql_pages ${pages.length}/${a.pages.length}`);const seen=new Set<number>(),headerByPage=new Map(a.pages.map((p:any)=>[Number(p.page),p]));let positions=0;for(const p of pages){const no=Number(p.page),header:any=headerByPage.get(no);if(!no||seen.has(no)||!header||Number(p.id)!==Number(header.id)||clean(p.pagePNG)!==clean(header.pagePNG))throw Error(`tesco_public_graphql_page_mismatch:${no}`);seen.add(no);positions+=Array.isArray(p.positions)?p.positions.length:0;}if(positions<1)throw Error('tesco_public_graphql_no_positions');return{...a,pages,public_positions:positions};}
type T={text:string;x:number;y:number;width:number;height:number;words:string[]};type C={price:number;old:number|null;x:number;y:number;kind:string;label:string;context:string};
function tok(items:any[]):T[]{return items.filter((q:any)=>typeof q.str==='string'&&clean(q.str)).map((q:any)=>({text:clean(q.str),x:Number(q.transform?.[4]||0),y:Number(q.transform?.[5]||0),width:Number(q.width||0),height:Math.abs(Number(q.height||q.transform?.[3]||q.transform?.[0]||0)),words:norm(q.str).split(' ').filter(Boolean)}));}
function around(t:T[],x:number,y:number,xr:number,yr:number){return clean(t.filter(q=>Math.abs(q.x-x)<=xr&&Math.abs(q.y-y)<=yr).sort((a,b)=>Math.abs(b.y-a.y)>4?b.y-a.y:a.x-b.x).map(q=>q.text).join(' '));}
function dec(v:string){const m=v.match(/^(\d{1,4})[,.](\d{2})$/);return m?Number(`${m[1]}.${m[2]}`):null;}
function pcs(t:T[]):C[]{const o:C[]=[];const cents=t.filter(q=>/^\d{2}$/.test(q.text)&&q.height>=7&&q.height<=16),whole=t.filter(q=>/^\d{1,4}$/.test(q.text)&&q.height>=17&&q.width>=10),ds=t.map(q=>({q,v:dec(q.text)})).filter(x=>x.v!==null)as any[];for(const w of whole){const c=cents.filter(q=>q.x>=w.x+w.width-4&&q.x<=w.x+w.width+24&&q.y>=w.y+2&&q.y<=w.y+16).sort((a,b)=>Math.hypot(w.x-a.x,w.y-a.y)-Math.hypot(w.x-b.x,w.y-b.y))[0];if(!c)continue;const price=Number(w.text)+Number(c.text)/100,old=ds.filter(x=>x.v>price&&Math.abs(x.q.x-w.x)<=34&&x.q.y>=w.y+10&&x.q.y<=w.y+58).sort((a,b)=>Math.abs(a.q.y-w.y)-Math.abs(b.q.y-w.y))[0],label=around(t,w.x,w.y,72,48),context=around(t,w.x,w.y,115,95),n=norm(label),nc=norm(context),kind=n.includes('cena pro vsechny')?'public':(n.includes('clubcard cena')||n.includes('s clubcard')||(old&&n.includes('clubcard'))?'clubcard':(!nc.includes('clubcard')?'public':'unknown'));o.push({price:Math.round(price*100)/100,old:old?.v||null,x:Math.round(w.x*10)/10,y:Math.round(w.y*10)/10,kind,label,context});}const seen=new Set();return o.filter(x=>{const k=`${x.price}|${x.x}|${x.y}`;if(seen.has(k))return false;seen.add(k);return true;});}
function kws(title:string){return[...new Set(norm(title).split(' ').filter(w=>w.length>=4&&!STOP.has(w)&&!/^\d+$/.test(w)))];}
function layoutScore(c:C,q:T){const dx=q.x-c.x,dy=Math.abs(q.y-c.y);return Math.hypot(Math.max(-12,dx),dy*2.15)+(dx<-12?150+Math.abs(dx)*1.35:0);}
function ev(title:string,c:C,t:T[]){const scores:any[]=[];for(const w of kws(title)){let best=Infinity;for(const q of t)if(q.words.includes(w))best=Math.min(best,layoutScore(c,q));if(best<=260)scores.push({w,s:best});}const mean=scores.length?scores.reduce((a,b)=>a+b.s,0)/scores.length:null,min=scores.length?Math.min(...scores.map(x=>x.s)):null;return{n:scores.length,words:scores.map(x=>x.w),mean,min,ok:scores.length>=2?(mean??999)<=190:scores.length===1&&(min??999)<=175};}
function hs(a:any,p:any,w:number,h:number){const out:any[]=[];for(const raw of p.positions||[]){const x=raw?.__ref?a.s[ref(raw)]:raw;if(!x?.products?.length)continue;const products=x.products.map((z:any)=>z?.__ref?a.s[ref(z)]:z).filter((z:any)=>z&&((z.__typename==='LeafletProduct')||z.id||z.product));const xp=Number(x.calculatedPositionX),yp=Number(x.calculatedPositionY),prs=products.map((z:any)=>z.id).filter((z:any)=>z!=null),main=products.find((z:any)=>z.isMainProduct===true)||products.find((z:any)=>z.product?.pngFileURL&&!String(z.product.pngFileURL).includes('placeholder-1.png'))||products[0],names=products.map((z:any)=>clean(z.promoOfferName||z.product?.productName)).filter(Boolean);if(Number.isFinite(xp)&&Number.isFinite(yp)&&names.length)out.push({id:x.id,x:w*xp/100,y:h-h*yp/100,prs,names,main});}return out;}
function best(h:any,c:C,t:T[]){return h.names.map((title:string)=>({title,e:ev(title,c,t)})).sort((a:any,b:any)=>(b.e.ok?1:0)-(a.e.ok?1:0)||b.e.n-a.e.n||(a.e.mean??9999)-(b.e.mean??9999))[0];}
const GLYPH:any={'Ű':'0','ű':'1','Ų':'2','ų':'3','Ŵ':'4','ŵ':'5','Ŷ':'6','ŷ':'7','Ÿ':'8','Ź':'9'};function decodeDigits(s:string){return[...s].map(ch=>GLYPH[ch]??ch).join('');}
type Q={value:number;unit:string;source:string};
function quantities(name:string):Q[]{const s=decodeDigits(clean(name)),out:Q[]=[];for(const m of s.matchAll(/(\d+)\s*[x×]\s*(\d+(?:[,.]\d+)?)\s*(kg|ml|g|l|ks)\b/gi)){const a=Number(m[1]),b=Number(m[2].replace(',','.'));if(a>0&&b>0)out.push({value:a*b,unit:m[3].toLowerCase(),source:m[0]});}for(const m of s.matchAll(/(\d+(?:[,.]\d+)?)\s*(kg|ml|g|l|ks)\b/gi)){const v=Number(m[1].replace(',','.'));if(v>0)out.push({value:v,unit:m[2].toLowerCase(),source:m[0]});}for(const m of s.matchAll(/\b(\d+)\s*[x×]\s*(\d+)\b/gi)){const a=Number(m[1]),b=Number(m[2]);if(a>0&&b>0)out.push({value:a*b,unit:'ks',source:m[0]});}const seen=new Set<string>();return out.filter(q=>{const k=`${q.value}|${q.unit}`;if(seen.has(k))return false;seen.add(k);return true;});}
function expectedUnit(price:number,q:Q){if(q.unit==='g'||q.unit==='ml')return price/q.value*100;if(q.unit==='kg'||q.unit==='l'||q.unit==='ks')return price/q.value;return null;}
function decimalsIn(s:string){const d=decodeDigits(s);return[...d.matchAll(/\b(\d{1,4})[,.](\d{2})\b/g)].map(m=>Number(`${m[1]}.${m[2]}`)).filter(Number.isFinite);}
function mathEvidence(h:any,c:C){const qs=quantities(clean(h.main?.product?.productName||'')),vals=decimalsIn(c.context),matches:any[]=[];for(const q of qs){const expected=expectedUnit(c.price,q);if(expected===null||!vals.length)continue;const nearest=vals.slice().sort((a,b)=>Math.abs(a-expected)-Math.abs(b-expected))[0],delta=Math.abs(nearest-expected);if(delta<=Math.max(.08,expected*.012))matches.push({q,expected,nearest,delta});}matches.sort((a,b)=>a.delta-b.delta);const m=matches[0];return m?{ok:true,quantity:m.q,expected:Math.round(m.expected*100)/100,nearest:m.nearest}:{ok:false,quantity:qs[0]||null,expected:null,nearest:null};}
function mathInfo(h:any,c:C,hot:any[]){const me=mathEvidence(h,c);if(!me.ok)return{...me,unique:false,matching_hotspots:0};const count=hot.filter(h2=>mathEvidence(h2,c).ok).length;return{...me,unique:count===1,matching_hotspots:count};}
function hungarian(a:number[][]){const n=a.length,m=a[0]?.length||0;if(!n||!m)return[];const u=Array(n+1).fill(0),v=Array(m+1).fill(0),p=Array(m+1).fill(0),way=Array(m+1).fill(0);for(let i=1;i<=n;i++){p[0]=i;let j0=0,minv=Array(m+1).fill(Infinity),used=Array(m+1).fill(false);do{used[j0]=true;let i0=p[j0],d=Infinity,j1=0;for(let j=1;j<=m;j++)if(!used[j]){let cur=a[i0-1][j-1]-u[i0]-v[j];if(cur<minv[j]){minv[j]=cur;way[j]=j0}if(minv[j]<d){d=minv[j];j1=j}}for(let j=0;j<=m;j++)used[j]?(u[p[j]]+=d,v[j]-=d):minv[j]-=d;j0=j1}while(p[j0]!==0);do{let j1=way[j0];p[j0]=p[j1];j0=j1}while(j0!==0)}const r=Array(n).fill(-1);for(let j=1;j<=m;j++)if(p[j]>0)r[p[j]-1]=j-1;return r;}
function assign(hot:any[],cs:C[],t:T[]){if(!hot.length)return{sparse:false,rows:[]};if(cs.length<Math.ceil(hot.length*.55))return{sparse:true,rows:hot.map((h:any)=>({...h,assigned:false}))};const eligible=hot.map((h:any,i:number)=>({h,i})).filter(({h}:any)=>cs.some(c=>best(h,c,t)?.e?.ok||mathInfo(h,c,hot).unique)),out=hot.map((h:any)=>({...h,assigned:false}));if(!eligible.length)return{sparse:false,rows:out};const work:any[]=[...cs];while(work.length<eligible.length)work.push(null);const mat=eligible.map(({h}:any)=>work.map(c=>{if(!c)return 30000;const b=best(h,c,t),mi=mathInfo(h,c,hot),sp=Math.hypot(h.x-c.x,h.y-c.y);if(!b?.e?.ok&&!mi.unique)return 12000+sp;const sem=b?.e?.ok?((b.e.mean??b.e.min)+sp*.015-b.e.n*12):260,bonus=b?.e?.ok&&mi.ok?220:(mi.unique?280:0);return sem-bonus;})),as=hungarian(mat);eligible.forEach(({h,i}:any,ri:number)=>{const ci=as[ri],c=ci>=0&&ci<cs.length?cs[ci]:null;if(!c)return;const b=best(h,c,t),mi=mathInfo(h,c,hot);if(!b?.e?.ok&&!mi.unique)return;out[i]={...h,assigned:true,ci,candidate:c,semantic_title:b?.title||'',semantic:b?.e||null,math:mi,spatial:Math.round(Math.hypot(h.x-c.x,h.y-c.y)*10)/10}});return{sparse:false,rows:out};}
Deno.serve(async req=>{if(req.method!=='POST')return resp({error:'method'},405);if(!allowed(req))return resp({error:'Unauthorized'},401);try{const b=await req.json().catch(()=>({})),start=Math.max(1,Math.min(39,Number(b.start_page||3))),count=Math.max(1,Math.min(39,Number(b.probe_pages||1))),requested=explicitViewer(b.viewer_url),v=requested||await viewer(),html=await text(v),header=apollo(html),a=await publicPages(header,v),expectedPdf=clean(b.expected_pdf_url);if(expectedPdf&&a.pdf!==expectedPdf)throw Error('pdf_snapshot_mismatch');const r=await fetch(a.pdf,{headers:{...H,referer:v},signal:AbortSignal.timeout(45000)}),bytes=new Uint8Array(await r.arrayBuffer()),doc=await pdfjs.getDocument({data:bytes,disableWorker:true,useSystemFonts:true}).promise;if(doc.numPages!==a.pages.length)throw Error(`tesco_pdf_pages ${doc.numPages}/${a.pages.length}`);const pages:any[]=[],rows:any[]=[];for(let no=start;no<=Math.min(doc.numPages,start+count-1);no++){const pg=await doc.getPage(no),tc:any=await pg.getTextContent(),t=tok(tc.items||[]),cs=pcs(t),ap=a.pages.find((x:any)=>Number(x.page)===no),hot=ap?hs(a,ap,Number(pg.view?.[2]||0),Number(pg.view?.[3]||0)):[],m=assign(hot,cs,t);if(!m.sparse)for(const x of m.rows)if(x.assigned&&x.candidate.kind==='public'){const lp=x.main,title=clean(lp?.promoOfferName||lp?.product?.productName),e=ev(title,x.candidate,t),mi=x.math;if(e.ok||mi?.unique)rows.push({page:no,position_id:x.id,main_id:lp?.id,title,product_name:clean(lp?.product?.productName),variant_count:x.prs.length,price:x.candidate.price,old_price:x.candidate.old,semantic_words:e.words,layout_score:Math.round((e.mean??e.min??0)*10)/10,math:mi,spatial:x.spatial,image:clean(lp?.product?.pngFileURL)});}pages.push({page:no,hotspots:hot.length,candidates:cs.length,sparse:m.sparse,assigned:m.rows.filter((x:any)=>x.assigned).length,public_rows:rows.filter(x=>x.page===no).length});}return resp({ok:true,adapter:'tesco-layout-v14-semantic-math',viewer_url:v,pdf_url:a.pdf,public_position_count:a.public_positions,row_count:rows.length,rows:rows.slice(0,200),pages});}catch(e){return resp({error:e instanceof Error?e.message:String(e)},500)}});
