update public.products
set filter_group = case
  when public.normalize_text(name) ~ '^(bozkov original|kozel 11|red label|billa l ubovnianka|bozkov standard|diana moravia|exclusive rulandske sede|jameson|l u sedmi kasen tuzemak|magnesia red|moravy vina z cech|mucha sekt|popstar tea|professorado|red bull|sklepy cejkovice|sol vineus|sommelier club|stara myslivecka|svijansky maz|tarapaca sekt|templarske sklepy tramin|tullamore d e w|v kozel 11|vinarstvi breclav|vinarstvi bzenec|zamecke ego vinarstvi|zlomek vavra palava|bitterol aperitiv|premium orange peel spritz|vinice hnanice|monster|velko popovicky kozel|multivitamin karlova koruna)' then 'drinks'
  when public.normalize_text(name) ~ '^(smetanito giga|billa n anuk|billa o kurky|dr oetker gel|novinka billa k uskus|opavia brumik|saturo nutricne kompletni jidlo|se budete tesit milora plnene trubicky|apetito smetanove|chef select nugety|food festival|kinder bueno mini|kinder vajicko s prekvapenim|opavia fidorka|opavia zlate esicka|orion lentilky|orion studentska pecet|storck merci together|chupa chups lizatko|corn flakes|pernik s naplni|jiska svetla vitana|jiska tmava vitana|kinder joy|tatranky opavia|tradicni pomazankove boni)' then 'food'
  when public.normalize_text(name) ~ '^(chilly gel|gel na skvrny|pletovy krem|colgate uv plax|lak okamzity objem|prostredek na myti nadobi|alpa francovka|cien penove tuzidlo)' then 'drugstore'
  when public.normalize_text(name) ~ '^grilovaci brikety' then 'garden'
  else filter_group
end,
updated_at = now()
where filter_group is null
  and public.normalize_text(name) ~ '^(bozkov original|kozel 11|red label|billa l ubovnianka|bozkov standard|diana moravia|exclusive rulandske sede|jameson|l u sedmi kasen tuzemak|magnesia red|moravy vina z cech|mucha sekt|popstar tea|professorado|red bull|sklepy cejkovice|sol vineus|sommelier club|stara myslivecka|svijansky maz|tarapaca sekt|templarske sklepy tramin|tullamore d e w|v kozel 11|vinarstvi breclav|vinarstvi bzenec|zamecke ego vinarstvi|zlomek vavra palava|bitterol aperitiv|premium orange peel spritz|vinice hnanice|monster|velko popovicky kozel|multivitamin karlova koruna|smetanito giga|billa n anuk|billa o kurky|dr oetker gel|novinka billa k uskus|opavia brumik|saturo nutricne kompletni jidlo|se budete tesit milora plnene trubicky|apetito smetanove|chef select nugety|food festival|kinder bueno mini|kinder vajicko s prekvapenim|opavia fidorka|opavia zlate esicka|orion lentilky|orion studentska pecet|storck merci together|chupa chups lizatko|corn flakes|pernik s naplni|jiska svetla vitana|jiska tmava vitana|kinder joy|tatranky opavia|tradicni pomazankove boni|chilly gel|gel na skvrny|pletovy krem|colgate uv plax|lak okamzity objem|prostredek na myti nadobi|alpa francovka|cien penove tuzidlo|grilovaci brikety)';