drop materialized view private.public_offer_search_cache_pre_store_fallback;

alter index private.public_offer_search_cache_v3_offer_id_uidx rename to public_offer_search_cache_offer_id_uidx;
alter index private.public_offer_search_cache_v3_group_idx rename to public_offer_search_cache_group_idx;
alter index private.public_offer_search_cache_v3_price_idx rename to public_offer_search_cache_price_idx;
alter index private.public_offer_search_cache_v3_product_search_trgm_idx rename to public_offer_search_cache_product_search_trgm_idx;
alter index private.public_offer_search_cache_v3_published_idx rename to public_offer_search_cache_published_idx;
alter index private.public_offer_search_cache_v3_region_idx rename to public_offer_search_cache_region_idx;
alter index private.public_offer_search_cache_v3_search_trgm_idx rename to public_offer_search_cache_search_trgm_idx;
alter index private.public_offer_search_cache_v3_semantic_tags_gin_idx rename to public_offer_search_cache_semantic_tags_gin_idx;
alter index private.public_offer_search_cache_v3_store_idx rename to public_offer_search_cache_store_idx;
alter index private.public_offer_search_cache_v3_validity_idx rename to public_offer_search_cache_validity_idx;