set local statement_timeout = '60s';

alter materialized view private.public_offer_search_cache rename to public_offer_search_cache_previous;
alter materialized view private.public_offer_search_cache_next rename to public_offer_search_cache;
drop materialized view private.public_offer_search_cache_previous;

alter index private.public_offer_search_cache_next_offer_id_uidx rename to public_offer_search_cache_offer_id_uidx;
alter index private.public_offer_search_cache_next_group_idx rename to public_offer_search_cache_group_idx;
alter index private.public_offer_search_cache_next_price_idx rename to public_offer_search_cache_price_idx;
alter index private.public_offer_search_cache_next_product_comparison_idx rename to public_offer_search_cache_product_comparison_idx;
alter index private.public_offer_search_cache_next_product_search_trgm_idx rename to public_offer_search_cache_product_search_trgm_idx;
alter index private.public_offer_search_cache_next_published_idx rename to public_offer_search_cache_published_idx;
alter index private.public_offer_search_cache_next_region_idx rename to public_offer_search_cache_region_idx;
alter index private.public_offer_search_cache_next_search_trgm_idx rename to public_offer_search_cache_search_trgm_idx;
alter index private.public_offer_search_cache_next_semantic_tags_gin_idx rename to public_offer_search_cache_semantic_tags_gin_idx;
alter index private.public_offer_search_cache_next_store_idx rename to public_offer_search_cache_store_idx;
alter index private.public_offer_search_cache_next_validity_idx rename to public_offer_search_cache_validity_idx;

grant all on table private.public_offer_search_cache to anon,authenticated,service_role;