select pg_advisory_xact_lock(hashtextextended('slevao:albert-publitas-v4', 0));
create temporary table _albert_batch_base on commit drop as
select p.*,coalesce(public.normalize_product_name(p.brand),'') brand_key,coalesce(public.product_quantity_key(p.quantity_text),'') qty_key,
 (exists(select 1 from public.offers x where x.product_id=p.id) or exists(select 1 from public.import_items x where x.product_id=p.id) or exists(select 1 from public.leaflet_import_items x where x.product_id=p.id) or exists(select 1 from public.notifications x where x.product_id=p.id) or exists(select 1 from public.offer_reports x where x.product_id=p.id) or exists(select 1 from public.price_alerts x where x.product_id=p.id) or exists(select 1 from public.price_history x where x.product_id=p.id) or exists(select 1 from public.product_equivalences x where x.product_id_a=p.id or x.product_id_b=p.id) or exists(select 1 from public.product_favorites x where x.product_id=p.id) or exists(select 1 from public.public_product_leaflet_locations x where x.product_id=p.id) or exists(select 1 from public.recently_viewed_products x where x.product_id=p.id) or exists(select 1 from public.shopping_list_items x where x.product_id=p.id) or exists(select 1 from private.offer_visual_fallback_candidates x where x.product_id=p.id) or exists(select 1 from private.product_taxonomy_backfill_log x where x.product_id=p.id) or exists(select 1 from private.product_taxonomy_candidates x where x.product_id=p.id)) hard_ref,
 (exists(select 1 from public.product_image_candidates x where x.product_id=p.id) or exists(select 1 from public.product_image_generation_jobs x where x.product_id=p.id) or exists(select 1 from public.product_image_library x where x.product_id=p.id)) image_ref
from public.products p where p.is_active=true and p.metadata->>'created_from_albert_publitas_text_v4'='true' and public.product_label_is_specific(p.name) and coalesce(btrim(p.brand),'')='' and left(p.normalized_name,1) in ('t','u','v','w');
create temporary table _albert_batch_eligible on commit drop as select b.normalized_name,b.brand_key,b.qty_key from _albert_batch_base b left join public.product_aliases a on a.product_id=b.id left join public.stores s on s.id=a.source_store_id group by 1,2,3 having count(distinct b.id)>1 and count(distinct nullif(regexp_replace(coalesce(b.ean,''),'\D','','g'),''))<=1 and count(distinct nullif(b.metadata->>'structured_identity_key',''))<=1 and count(distinct nullif(b.metadata->>'kaufland_kl_nr',''))<=1 and count(distinct a.normalized_alias)=1 and count(distinct a.source_store_id)=1 and bool_and(coalesce(s.slug,'')='albert') filter(where a.product_id is not null);
create temporary table _albert_batch_ranked on commit drop as select b.*,row_number() over(partition by b.normalized_name,b.brand_key,b.qty_key order by b.hard_ref desc,b.image_ref desc,(coalesce(b.ean,'')<>'') desc,(coalesce(b.metadata->>'structured_identity_key','')<>'') desc,(coalesce(b.metadata->>'kaufland_kl_nr','')<>'') desc,b.image_verified desc,b.is_verified desc,b.created_at,b.id) rn from _albert_batch_base b join _albert_batch_eligible e using(normalized_name,brand_key,qty_key);
create temporary table _albert_batch_mapping on commit drop as select d.id duplicate_id,c.id canonical_id,d.normalized_name original_normalized_name,d.brand_key,d.qty_key from _albert_batch_ranked d join _albert_batch_ranked c on c.normalized_name=d.normalized_name and c.brand_key=d.brand_key and c.qty_key=d.qty_key and c.rn=1 where d.rn>1 and d.hard_ref=false and d.image_ref=false and coalesce(d.ean,'')='' and coalesce(d.metadata->>'structured_identity_key','')='' and coalesce(d.metadata->>'kaufland_kl_nr','')='';
do $guard$ declare v_count integer; v_clusters integer; begin select count(*),count(distinct (original_normalized_name,brand_key,qty_key)) into v_count,v_clusters from _albert_batch_mapping; if v_count<>4252 or v_clusters<>17 then raise exception 'Albert TUVW cleanup drifted: % rows / % clusters; expected 4252 / 17.',v_count,v_clusters; end if; end $guard$;
with alias_source as (select distinct on (m.canonical_id,a.normalized_alias) m.canonical_id,a.alias,a.normalized_alias,a.brand,a.quantity_text,a.source_store_id,a.confidence,a.created_at from public.product_aliases a join _albert_batch_mapping m on m.duplicate_id=a.product_id order by m.canonical_id,a.normalized_alias,a.confidence desc,a.created_at,a.id) insert into public.product_aliases(product_id,alias,normalized_alias,brand,quantity_text,source_store_id,confidence,created_at,updated_at) select canonical_id,alias,normalized_alias,brand,quantity_text,source_store_id,confidence,created_at,now() from alias_source on conflict(product_id,normalized_alias) do update set confidence=greatest(public.product_aliases.confidence,excluded.confidence),brand=coalesce(public.product_aliases.brand,excluded.brand),quantity_text=coalesce(public.product_aliases.quantity_text,excluded.quantity_text),source_store_id=coalesce(public.product_aliases.source_store_id,excluded.source_store_id),updated_at=now();
delete from public.product_aliases a using _albert_batch_mapping m where a.product_id=m.duplicate_id;
update public.products p set is_active=false,normalized_name='__inactive_albert_v4_duplicate__:'||p.id::text,metadata=coalesce(p.metadata,'{}'::jsonb)||jsonb_build_object('_duplicate_deactivation_policy','albert_v4_unbranded_single_alias_v1','_duplicate_original_normalized_name',m.original_normalized_name,'_duplicate_canonical_product_id',m.canonical_id,'_duplicate_deactivated_at',now()),updated_at=now() from _albert_batch_mapping m where p.id=m.duplicate_id and p.is_active=true;
