create table if not exists private.automation_watchdog_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'running' check (status in ('running','ok','error')),
  summary jsonb not null default '{}'::jsonb,
  error_message text
);

create table if not exists private.automation_watchdog_incidents (
  id bigint generated by default as identity primary key,
  fingerprint text not null unique,
  incident_type text not null,
  severity text not null default 'warning' check (severity in ('info','warning','error','critical')),
  store_slug text,
  job_id bigint,
  request_id bigint,
  status text not null default 'open' check (status in ('open','resolved')),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  resolved_at timestamptz,
  occurrences integer not null default 1,
  details jsonb not null default '{}'::jsonb
);

create index if not exists automation_watchdog_incidents_open_idx
  on private.automation_watchdog_incidents(status,last_seen_at desc);
create index if not exists automation_watchdog_runs_started_idx
  on private.automation_watchdog_runs(started_at desc);

revoke all on table private.automation_watchdog_runs from public,anon,authenticated;
revoke all on table private.automation_watchdog_incidents from public,anon,authenticated;

create or replace function private.record_automation_watchdog_incident(
  p_fingerprint text,
  p_incident_type text,
  p_severity text default 'warning',
  p_store_slug text default null,
  p_job_id bigint default null,
  p_request_id bigint default null,
  p_details jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path to 'private','public','pg_temp'
as $function$
begin
  insert into private.automation_watchdog_incidents(
    fingerprint,incident_type,severity,store_slug,job_id,request_id,status,
    first_seen_at,last_seen_at,resolved_at,occurrences,details
  ) values(
    p_fingerprint,p_incident_type,p_severity,p_store_slug,p_job_id,p_request_id,'open',
    now(),now(),null,1,coalesce(p_details,'{}'::jsonb)
  )
  on conflict(fingerprint) do update set
    incident_type=excluded.incident_type,
    severity=excluded.severity,
    store_slug=coalesce(excluded.store_slug,private.automation_watchdog_incidents.store_slug),
    job_id=coalesce(excluded.job_id,private.automation_watchdog_incidents.job_id),
    request_id=coalesce(excluded.request_id,private.automation_watchdog_incidents.request_id),
    status='open',
    last_seen_at=now(),
    resolved_at=null,
    occurrences=private.automation_watchdog_incidents.occurrences+1,
    details=excluded.details;
end;
$function$;

revoke all on function private.record_automation_watchdog_incident(text,text,text,text,bigint,bigint,jsonb) from public,anon,authenticated;

create or replace function private.run_automation_watchdog()
returns jsonb
language plpgsql
security definer
set search_path to 'public','private','cron','net','pg_temp'
as $function$
declare
  v_run_id bigint;
  v_started timestamptz := clock_timestamp();
  v_stale_locks integer := 0;
  v_stale_imports integer := 0;
  v_stale_kaufland integer := 0;
  v_rollover_recovered boolean := false;
  v_rollover_result jsonb := '{}'::jsonb;
  v_latest_rollover record;
  v_cron_incidents integer := 0;
  v_http_incidents integer := 0;
  v_health_incidents integer := 0;
  v_resolved integer := 0;
  v_deleted_incidents integer := 0;
  v_deleted_runs integer := 0;
  r record;
begin
  insert into private.automation_watchdog_runs(status) values('running') returning id into v_run_id;

  v_stale_locks := public.release_stale_product_sync_locks();
  v_stale_imports := public.cleanup_stale_leaflet_imports();
  v_stale_kaufland := public.cleanup_stale_kaufland_product_sync_audits(interval '30 minutes');

  select rjd.runid,rjd.status,rjd.start_time,rjd.end_time,rjd.return_message
    into v_latest_rollover
  from cron.job j
  left join lateral (
    select x.runid,x.status,x.start_time,x.end_time,x.return_message
    from cron.job_run_details x
    where x.jobid=j.jobid
    order by x.start_time desc
    limit 1
  ) rjd on true
  where j.active=true and j.jobname='slevao-rollover-supervisor'
  limit 1;

  if v_latest_rollover.runid is null
     or v_latest_rollover.start_time < now()-interval '12 minutes'
     or coalesce(v_latest_rollover.status,'') <> 'succeeded' then
    begin
      v_rollover_result := public.run_rollover_supervisor();
      v_rollover_recovered := true;
    exception when others then
      perform private.record_automation_watchdog_incident(
        'rollover-supervisor-recovery','rollover_supervisor_failure','critical',null,null,null,
        jsonb_build_object('error',sqlerrm,'latest_run',to_jsonb(v_latest_rollover))
      );
    end;
  end if;

  for r in
    with latest as (
      select distinct on (j.jobid)
        j.jobid,j.jobname,j.schedule,x.runid,x.status,x.start_time,x.end_time,x.return_message
      from cron.job j
      join cron.job_run_details x on x.jobid=j.jobid
      where j.active=true
      order by j.jobid,x.start_time desc
    )
    select * from latest
    where coalesce(status,'') <> 'succeeded'
      and start_time >= now()-interval '2 hours'
  loop
    perform private.record_automation_watchdog_incident(
      format('cron:%s:%s',r.jobid,r.runid),'cron_failure','error',null,r.jobid,null,
      jsonb_build_object('jobname',r.jobname,'schedule',r.schedule,'runid',r.runid,'status',r.status,
        'start_time',r.start_time,'end_time',r.end_time,'return_message',left(coalesce(r.return_message,''),1000))
    );
    v_cron_incidents := v_cron_incidents+1;
  end loop;

  for r in
    select id,created,status_code,timed_out,error_msg,content
    from net._http_response
    where created >= now()-interval '20 minutes'
      and (coalesce(timed_out,false)=true or coalesce(status_code,0)>=400 or error_msg is not null)
  loop
    perform private.record_automation_watchdog_incident(
      format('http:%s',r.id),'http_failure',case when coalesce(r.timed_out,false) then 'error' else 'warning' end,
      null,null,r.id,jsonb_build_object('created',r.created,'status_code',r.status_code,'timed_out',r.timed_out,
        'error',left(coalesce(r.error_msg,''),1000),'content',left(coalesce(r.content,''),1200))
    );
    v_http_incidents := v_http_incidents+1;
  end loop;

  for r in
    select s.slug,st.store_id,st.last_offer_count,st.last_success_at,st.health_reason
    from public.store_product_sync_state st
    join public.stores s on s.id=st.store_id
    where st.health_status='ok'
      and not exists (
        select 1 from public.offers o
        where o.store_id=st.store_id and o.status='published' and o.is_verified=true
          and o.valid_from <= (now() at time zone 'Europe/Prague')::date
          and o.valid_to >= (now() at time zone 'Europe/Prague')::date
      )
  loop
    perform private.record_automation_watchdog_incident(
      format('health-zero:%s',r.slug),'health_ok_without_current_offers','critical',r.slug,null,null,
      jsonb_build_object('last_offer_count',r.last_offer_count,'last_success_at',r.last_success_at,'health_reason',r.health_reason)
    );
    v_health_incidents := v_health_incidents+1;
  end loop;

  update private.automation_watchdog_incidents
     set status='resolved',resolved_at=now()
   where status='open'
     and incident_type in ('cron_failure','http_failure','health_ok_without_current_offers','rollover_supervisor_failure')
     and last_seen_at < now()-interval '30 minutes';
  get diagnostics v_resolved = row_count;

  delete from private.automation_watchdog_incidents where status='resolved' and resolved_at < now()-interval '30 days';
  get diagnostics v_deleted_incidents = row_count;
  delete from private.automation_watchdog_runs where id<>v_run_id and started_at < now()-interval '30 days';
  get diagnostics v_deleted_runs = row_count;

  update private.automation_watchdog_runs
     set finished_at=clock_timestamp(),status='ok',summary=jsonb_build_object(
       'stale_locks_released',v_stale_locks,'stale_imports_cleaned',v_stale_imports,
       'stale_kaufland_audits_cleaned',v_stale_kaufland,'rollover_recovered',v_rollover_recovered,
       'rollover_result',v_rollover_result,'cron_incidents_seen',v_cron_incidents,
       'http_incidents_seen',v_http_incidents,'health_incidents_seen',v_health_incidents,
       'incidents_resolved',v_resolved,'old_incidents_deleted',v_deleted_incidents,
       'old_runs_deleted',v_deleted_runs,'duration_ms',round(extract(epoch from (clock_timestamp()-v_started))*1000)
     )
   where id=v_run_id;

  return (select summary from private.automation_watchdog_runs where id=v_run_id);
exception when others then
  if v_run_id is not null then
    update private.automation_watchdog_runs
       set finished_at=clock_timestamp(),status='error',error_message=left(sqlerrm,2000),
           summary=jsonb_build_object('duration_ms',round(extract(epoch from (clock_timestamp()-v_started))*1000))
     where id=v_run_id;
  end if;
  raise;
end;
$function$;

revoke all on function private.run_automation_watchdog() from public,anon,authenticated;

do $$
declare v_job bigint;
begin
  select jobid into v_job from cron.job where jobname='slevao-automation-watchdog';
  if v_job is not null then perform cron.unschedule(v_job); end if;
  perform cron.schedule('slevao-automation-watchdog','*/10 * * * *',$cron$select private.run_automation_watchdog();$cron$);
end $$;
