update public.products
set filter_group = case
  when public.normalize_text(name) ~ '^(agro jesenice cesky hrasek|alibona brusinky|bebe brumik cokoladovy|bio spaldova kostka|bobik smetanovy krem|bohemia vroubky|chupa chups lizatka|coppenrath wiese dort|delika coleslaw|dyne maslova krajena|emco biskiti|emco polstarky vanilkove|freee cokoladove hvezdicky|garden gourmet vegetarianska jidla|hame majka|hreben tvarohovy|hubba bubba zvykacky|ibk trade rozinky|k classic lesni smes|k classic mini mix ovoce multipack|k classic pistacie|k classic zmrzlinove misky vaflove|k jarmark bavorska sekana|k jarmark karotka sacek|k jarmark kysane podmasli|k jarmark lizatka|k jarmark mramorova babovka|k jarmark vysocina|kalma toskanske rostlinne nudlicky|kalma trhane rostlinne kousky|kgold tiramisu|kinder crispy|kinder happy hippo|klasa povidlacky linecke rohlicky|kmotrovky uherakove|kunin kremova do omacek|kunin parizska slehacka|leimer smazene krupave kulicky|liptov ostiepok|louhovany preclik|madeta lipanek|madeta lipanek smetanovy extra|med bohemia kvetovy med|mega money jedly papir|meining masova konzerva|merci bonboniera|milka tender cow|milkeffekt janosikuv ostiepok|odkolek slovanske seminko|olma tradicni pomazankove|olz strudl makovy|opavia kolonada|opavia zlate polomacene|paw patrol ochucena brcka|perla hummus|pez figurka|philadelphia milka|rama cremefine|schar panini|vidal ocean jelly|vitacup suche plody|vitana instantni polevka|vitana poctiva gulasova polevka|vitana sypka smes pernik|viva kren|viva utopenci|x life cukrova vata|zozole pasky|zvykacky)' then 'food'
  when public.normalize_text(name) ~ '^(ambi pur osvez|bevola koule do koupele|bulldog myci gel|calgon odstranovac vodniho kamene|denim deospray black|denim voda po holeni|gillette gelstick|laguna parfem na pradlo|mixa telovy krem|palette barva na vlasy|peo sprej na nohy|pulirapid koupelna a kuchyne|sanytol odstranovac skvrn|woolite prostredek na prani)' then 'drugstore'
  when public.normalize_text(name) ~ '^k carinura miska pro zvirata' then 'pets'
  when public.normalize_text(name) ~ '^sheron ubrousky na palubni desku' then 'auto'
  when public.normalize_text(name) ~ '^(kuchynske uterky 50 x 70 cm|silvercrest formy na mini babovky|silvercrest formy na muffiny|silvercrest formy na tartaletky|silvercrest vakuovaci folie|spice soul plastove misky|spice soul plastovy poharek|vakuove pytle 5 kusu)' then 'home'
  else filter_group
end,
updated_at = now()
where filter_group is null
  and (
    public.normalize_text(name) ~ '^(agro jesenice cesky hrasek|alibona brusinky|bebe brumik cokoladovy|bio spaldova kostka|bobik smetanovy krem|bohemia vroubky|chupa chups lizatka|coppenrath wiese dort|delika coleslaw|dyne maslova krajena|emco biskiti|emco polstarky vanilkove|freee cokoladove hvezdicky|garden gourmet vegetarianska jidla|hame majka|hreben tvarohovy|hubba bubba zvykacky|ibk trade rozinky|k classic lesni smes|k classic mini mix ovoce multipack|k classic pistacie|k classic zmrzlinove misky vaflove|k jarmark bavorska sekana|k jarmark karotka sacek|k jarmark kysane podmasli|k jarmark lizatka|k jarmark mramorova babovka|k jarmark vysocina|kalma toskanske rostlinne nudlicky|kalma trhane rostlinne kousky|kgold tiramisu|kinder crispy|kinder happy hippo|klasa povidlacky linecke rohlicky|kmotrovky uherakove|kunin kremova do omacek|kunin parizska slehacka|leimer smazene krupave kulicky|liptov ostiepok|louhovany preclik|madeta lipanek|madeta lipanek smetanovy extra|med bohemia kvetovy med|mega money jedly papir|meining masova konzerva|merci bonboniera|milka tender cow|milkeffekt janosikuv ostiepok|odkolek slovanske seminko|olma tradicni pomazankove|olz strudl makovy|opavia kolonada|opavia zlate polomacene|paw patrol ochucena brcka|perla hummus|pez figurka|philadelphia milka|rama cremefine|schar panini|vidal ocean jelly|vitacup suche plody|vitana instantni polevka|vitana poctiva gulasova polevka|vitana sypka smes pernik|viva kren|viva utopenci|x life cukrova vata|zozole pasky|zvykacky|ambi pur osvez|bevola koule do koupele|bulldog myci gel|calgon odstranovac vodniho kamene|denim deospray black|denim voda po holeni|gillette gelstick|laguna parfem na pradlo|mixa telovy krem|palette barva na vlasy|peo sprej na nohy|pulirapid koupelna a kuchyne|sanytol odstranovac skvrn|woolite prostredek na prani|k carinura miska pro zvirata|sheron ubrousky na palubni desku|kuchynske uterky 50 x 70 cm|silvercrest formy na mini babovky|silvercrest formy na muffiny|silvercrest formy na tartaletky|silvercrest vakuovaci folie|spice soul plastove misky|spice soul plastovy poharek|vakuove pytle 5 kusu)'
  );
