import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const CRON=Deno.env.get('CRON_SECRET')||'';
const db=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
const CORS={'access-control-allow-origin':'*','access-control-allow-headers':'authorization,apikey,content-type,x-cron-secret','access-control-allow-methods':'POST,OPTIONS','content-type':'application/json; charset=utf-8'};
const FETCH_HEADERS={'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/150 Safari/537.36',accept:'text/html,application/json,*/*;q=0.8','accept-language':'cs-CZ,cs;q=0.9'};

function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:CORS});}
async function allowed(request:Request){const raw=request.headers.get('authorization')||'',token=raw.replace(/^Bearer\s+/i,'').trim();if(token===SERVICE)return true;if(CRON&&request.headers.get('x-cron-secret')===CRON)return true;if(!token)return false;const{data,error}=await db.auth.getUser(token);return!error&&!!data.user&&['admin','editor'].includes(String(data.user.app_metadata?.role||'').toLowerCase());}
async function fetchText(url:string,timeout=25000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const response=await fetch(url,{headers:FETCH_HEADERS,redirect:'follow',signal:controller.signal});const text=await response.text();if(!response.ok)throw new Error(`${new URL(url).hostname} HTTP ${response.status}`);return text}finally{clearTimeout(timer)}}
async function fetchOptionalJson(url:string){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const response=await fetch(url,{headers:FETCH_HEADERS,redirect:'follow',signal:controller.signal});if(!response.ok)return null;return await response.json().catch(()=>null)}finally{clearTimeout(timer)}}
function dataFromHtml(html:string){const marker='var data =',start=html.indexOf(marker),jsonStart=html.indexOf('{',start+marker.length),end=html.indexOf('Reader.Bootstrap.init',jsonStart);if(start<0||jsonStart<0||end<0)throw new Error('Publitas data mají neočekávaný formát.');const block=html.slice(jsonStart,end),semi=block.lastIndexOf(';');return JSON.parse((semi>=0?block.slice(0,semi):block).trim())}
function norm(value:string){return value.toLocaleLowerCase('cs').replace(/[^a-z0-9áčďéěíňóřšťúůýž]+/giu,' ').trim().replace(/\s+/g,' ')}
function isoFromCz(value:string){const m=value.match(/(\d{1,2})\.(\d{1,2})\.(\d{4})/u);if(!m)return null;return `${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`}
function addDays(iso:string,days:number){const d=new Date(`${iso}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)}
function clean(line:string){return line.replace(/\s+/g,' ').replace(/[,:;]+$/u,'').trim()}
const ARTICLE=/^\d{6,8}$/u;
const PRICE=/^\d{2,4}$/u;
const UNIT_PRICE=/^\d+(?:[,.]\d+)?\s*\/\s*(?:ks|kg|litr|l|m|100\s*g|100\s*ml)\b/iu;
const PAGE_NO=/^0?\d{1,2}$/u;
const NOISE=/(?:PLATNOST OD|Obrázky jsou příklady|Obrázek vytvořený|Vsechny ceny jsou|SOUTĚŽ|ROZJEĎTE TO|ZPÁTKY DO ŠKOLY|VÍC |NABÍDEK|KAŽDÝ ŠKOLNÍ|PŘESTÁVK|PRAVÉ FANOUŠKY|VÝHODY NA SRPEN|BALENÍ$|myKiK|aplikaci)/iu;
const DESC=/(?:\bvel\.|\bza$|\bza\b|\brůzn|\bbarv|\bcca\b|\b100%|\bks\b|\bcm\b|\bml\b|\bkg\b|\blitr\b|\bbavlna\b|\bprůměru\b|\bod$)/iu;
const GENERIC=/^(?:Dětská|Dětské|Dámská|Dámské|Pánská|Pánské|různá provedení|různé barvy|za|od)$/iu;
function allCaps(value:string){const letters=value.replace(/[^A-Za-zÁ-ž]/gu,'');return letters.length>=5&&letters===letters.toLocaleUpperCase('cs')}
function usableRoot(line:string){const t=clean(line);if(!t||t.length<3||t.length>60||ARTICLE.test(t)||PRICE.test(t)||PAGE_NO.test(t)||UNIT_PRICE.test(t)||NOISE.test(t)||DESC.test(t)||allCaps(t))return false;return /^[A-ZÁČĎÉĚÍŇÓŘŠŤÚŮÝŽ]/u.test(t)}
function appendable(line:string){const t=clean(line);if(!t||t.length>32||/^[A-ZÁČĎÉĚÍŇÓŘŠŤÚŮÝŽ]/u.test(t)||/[,:;]/u.test(line)||ARTICLE.test(t)||PRICE.test(t)||UNIT_PRICE.test(t)||NOISE.test(t)||DESC.test(t))return false;return /^[a-záčďéěíňóřšťúůýž]/u.test(t)}
function findDescriptor(lines:string[],priceIndex:number){for(let j=priceIndex-1;j>=Math.max(0,priceIndex-6);j--){const t=clean(lines[j]);if(/\bza\b/iu.test(t)||/\bza$/iu.test(t))return j;}return -1}
function findTitle(lines:string[],descriptorIndex:number){for(let j=descriptorIndex-1;j>=Math.max(0,descriptorIndex-9);j--){const root=clean(lines[j]);if(!usableRoot(root))continue;const parts=[root];for(let k=j+1;k<descriptorIndex&&parts.length<3;k++){if(appendable(lines[k]))parts.push(clean(lines[k]));}
 const title=parts.join(' ').replace(/\s+/g,' ').trim();if(!GENERIC.test(title)&&title.length>=4&&title.length<=72)return title;}
 return ''}
function parsePage(text:string,page:number){const lines=String(text||'').split(/\r?\n/u).map(clean).filter(Boolean);let validFrom:string|null=null;for(const line of lines){if(/PLATNOST OD/iu.test(line)){validFrom=isoFromCz(line);if(validFrom)break;}}
 if(!validFrom)return[];const validTo=addDays(validFrom,13),rows:any[]=[];for(let i=0;i<lines.length;i++){if(!PRICE.test(lines[i]))continue;const price=Number(lines[i]);if(!Number.isFinite(price)||price<15||price>5000)continue;const descriptor=findDescriptor(lines,i);if(descriptor<0)continue;const title=findTitle(lines,descriptor);if(!title)continue;let article='';for(let j=Math.max(0,descriptor-2);j<=Math.min(lines.length-1,i+4);j++){if(ARTICLE.test(lines[j])){article=lines[j];break;}}
 const isFrom=lines.slice(Math.max(0,descriptor-2),i).some(x=>/^od$/iu.test(x));rows.push({title,normalized_title:norm(title),price,valid_from:validFrom,valid_to:validTo,source_page:page,article_id:article||null,is_from_price:isFrom,confidence:article?0.97:0.93});}
 return rows}

type ProductRef={id:string;title:string;price:number};
function walkProducts(value:unknown,output:Map<string,ProductRef>){if(value==null)return;if(Array.isArray(value)){for(const item of value)walkProducts(item,output);return;}if(typeof value!=='object')return;const obj=value as Record<string,unknown>,id=String(obj.id??obj.productId??obj.product_id??'').trim(),title=String(obj.title??obj.name??'').replace(/\s+/g,' ').trim(),rawPrice=obj.price??obj.salePrice??obj.sale_price,price=typeof rawPrice==='number'?rawPrice:Number(String(rawPrice??'').replace(',','.'));if(/^\d{3,12}$/u.test(id)&&title.length>=2&&Number.isFinite(price)&&price>0&&price<100000&&!output.has(id))output.set(id,{id,title,price});for(const child of Object.values(obj))walkProducts(child,output)}

Deno.serve(async request=>{if(request.method==='OPTIONS')return new Response('ok',{headers:CORS});if(request.method!=='POST')return json({error:'Method not allowed'},405);if(!(await allowed(request)))return json({error:'Unauthorized'},401);try{const body=await request.json().catch(()=>({}));if(body.dry_run!==true)return json({error:'KiK produktová publikace zatím není povolena; použij dry_run.'},409);const{data:store,error:storeError}=await db.from('stores').select('id').eq('slug','kik').single();if(storeError||!store)throw storeError||new Error('KiK obchod nebyl nalezen.');const{data:document,error:documentError}=await db.from('leaflet_imports').select('id,source_hash,detected_valid_from,detected_valid_to,metadata').eq('store_id',store.id).eq('status','published').contains('metadata',{adapter:'kik-publitas-v1'}).order('created_at',{ascending:false}).limit(1).single();if(documentError||!document)throw documentError||new Error('Aktuální KiK Publitas dokument nebyl nalezen.');const viewer=String(document.metadata?.viewer_url||'').replace(/\/+$/u,'');if(!/^https:\/\/letaki\.kik\.cz\//iu.test(viewer))throw new Error('KiK dokument nemá povolenou viewer adresu.');const html=await fetchText(`${viewer}/`),data=dataFromHtml(html),cacheToken=String(data.cacheToken||'');if(!cacheToken)throw new Error('KiK Publitas nevrátil cacheToken.');const spreads=JSON.parse(await fetchText(`${viewer}/spreads.json?version=${encodeURIComponent(cacheToken)}`));if(!Array.isArray(spreads)||!spreads.length)throw new Error('KiK Publitas nevrátil stránky.');const structured=new Map<string,ProductRef>(),parsed:any[]=[];let hotspotFiles=0,pages=0;for(const spread of spreads){const spreadPages=Array.isArray(spread?.pages)?spread.pages:[],nums=spreadPages.map((p:any)=>Number(p?.number||0)).filter((n:number)=>n>0);if(nums.length){const hotspotData=await fetchOptionalJson(`${viewer}/page/${nums.join('-')}/hotspots_data.json?version=${encodeURIComponent(cacheToken)}`);if(hotspotData){hotspotFiles++;walkProducts(hotspotData,structured)}}for(const page of spreadPages){pages++;parsed.push(...parsePage(String(page?.text||''),Number(page?.number||pages)))}}
 const best=new Map<string,any>();for(const row of parsed){const key=`${row.normalized_title}|${row.valid_from}|${row.valid_to}`,prev=best.get(key);if(!prev||row.price<prev.price)best.set(key,row);}const rows=[...best.values()].sort((a,b)=>a.title.localeCompare(b.title,'cs')||a.price-b.price);return json({ok:true,dry_run:true,store:'KiK',document_id:document.id,publication_id:document.metadata?.publication_id||null,pages,hotspot_files:hotspotFiles,structured_products:structured.size,raw_candidates:parsed.length,publishable:rows.length,valid_from:rows.map(r=>r.valid_from).sort()[0]||null,valid_to:rows.map(r=>r.valid_to).sort().at(-1)||null,samples:rows.slice(0,140)});}catch(error){const message=error instanceof Error?error.message:String(error);return json({error:message,code:'KIK_PRODUCT_DRY_RUN_FAILED'},500)}});
