import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const U=Deno.env.get('SUPABASE_URL')!,K=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,C=Deno.env.get('CRON_SECRET')||'';
const db=createClient(U,K,{auth:{persistSession:false,autoRefreshToken:false}}),H={'content-type':'application/json; charset=utf-8'};
const J=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H}),clean=(v:any)=>String(v??'').replace(/\s+/g,' ').trim(),norm=(v:any)=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),letters=(s:string)=>(s.match(/[A-Za-zÁ-ž]/g)||[]).length;
function ok(r:Request){return r.headers.get('authorization')===`Bearer ${K}`||Boolean(C&&r.headers.get('x-cron-secret')===C)}
type W={text:string,left:number,top:number,width:number,height:number,confidence:number|string|null,block?:number,paragraph?:number,line?:number};
type L={text:string,titleText:string,left:number,right:number,top:number,bottom:number,cx:number,conf:number,titleConf:number,priceConf:number,maxHeight:number};
function directDecimal(s:string){const m=clean(s).match(/(?:^|[^0-9])(\d{1,4})[,.](\d{2})(?:[^0-9]|$)/);if(!m)return null;const v=Number(m[1])+Number(m[2])/100;return Number.isFinite(v)&&v>=2&&v<=5000?Math.round(v*100)/100:null}
function lines(words:W[]):L[]{const g=new Map<string,W[]>();for(const w of words||[]){if(!clean(w.text))continue;const k=`${w.block??0}|${w.paragraph??0}|${w.line??Math.round(Number(w.top)/8)}`;const a=g.get(k)||[];a.push(w);g.set(k,a)}return[...g.values()].map(a=>{a.sort((x,y)=>Number(x.left)-Number(y.left));const left=Math.min(...a.map(w=>Number(w.left))),right=Math.max(...a.map(w=>Number(w.left)+Number(w.width||0))),top=Math.min(...a.map(w=>Number(w.top))),bottom=Math.max(...a.map(w=>Number(w.top)+Number(w.height||0)));const scored=a.map(w=>({w,c:Number(w.confidence||0),hasLetters:letters(clean(w.text))>0,hasPrice:directDecimal(clean(w.text))!==null}));const cs=scored.map(x=>x.c).filter(Number.isFinite),alphaCs=scored.filter(x=>x.hasLetters&&Number.isFinite(x.c)).map(x=>x.c),priceCs=scored.filter(x=>x.hasPrice&&Number.isFinite(x.c)).map(x=>x.c),titleTokens=scored.filter(x=>x.hasLetters||x.c>=55).map(x=>clean(x.w.text)).filter(Boolean);const avg=(v:number[])=>v.length?v.reduce((x,y)=>x+y,0)/v.length:0;return{text:clean(a.map(w=>w.text).join(' ')),titleText:clean(titleTokens.join(' ')),left,right,top,bottom,cx:(left+right)/2,conf:avg(cs),titleConf:alphaCs.length?avg(alphaCs):avg(cs),priceConf:priceCs.length?Math.max(...priceCs):avg(cs),maxHeight:Math.max(...a.map(w=>Number(w.height||0)))}}).sort((a,b)=>a.top-b.top||a.left-b.left)}
function unitMarker(s:string){const n=norm(s);return /\b(?:100\s*(?:g|ml)|1\s*(?:kg|l|ks))\b.*(?:=|od)/.test(n)||/(?:^|\s)od\s+\d/.test(n)||/\/(?:kg|l|100\s*g|100\s*ml)\b/.test(n)}
function qty(s:string){const n=norm(s);if(unitMarker(s)||/\bcca\b/.test(n)||/\/(?:kg|l|ks)\b/.test(n))return null;let m=n.match(/\b(\d{1,2})\s*[x×]\s*(\d+(?:[,.]\d+)?)\s*(g|kg|ml|l|ks)\b/);if(m){const count=Number(m[1]),amount=Number(m[2].replace(',','.')),unit=m[3],total=count*amount;if(!Number.isFinite(total)||count<=0||amount<=0||count>100)return null;if((unit==='kg'||unit==='l')&&total>5)return null;if((unit==='g'||unit==='ml')&&total>5000)return null;if(unit==='ks'&&total>100)return null;return`${m[1]} x ${m[2].replace('.',',')} ${unit}`}m=n.match(/\b(\d+(?:[,.]\d+)?)\s*(g|kg|ml|l|ks)\b/);if(!m)return null;const amount=Number(m[1].replace(',','.')),unit=m[2];if(!Number.isFinite(amount)||amount<=0)return null;if((unit==='kg'||unit==='l')&&amount>5)return null;if((unit==='g'||unit==='ml')&&amount>5000)return null;if(unit==='ks'&&amount>100)return null;return`${m[1].replace('.',',')} ${unit}`}
function promo(s:string){return/(pri koupi|kup \d+|kup vic|ziskej|zaplat|kupon|karta|aplikac|nabidka|neplati|prodejna|dph|zdarma|cena od|cena s|sleva|usetris)/i.test(norm(s))}
function titlePartOK(s:string){const c=clean(s),n=norm(c);if(letters(c)<3||c.length<3||c.length>90||promo(c)||qty(c)||directDecimal(c)!==null)return false;if(/\b(100\s*g|100\s*ml|1\s*kg\s*=|1\s*l\s*=)\b/.test(n))return false;return true}
function buildTitle(ls:L[],price:L,qLine:L){const candidates=ls.filter(l=>l!==price&&l!==qLine&&l.titleConf>=72&&l.maxHeight<=45&&titlePartOK(l.titleText)&&Math.abs(l.cx-qLine.cx)<=155&&Math.abs(l.top-qLine.top)<=115);if(!candidates.length)return null;const nearest=candidates.slice().sort((a,b)=>(Math.abs(a.top-qLine.top)+Math.abs(a.cx-qLine.cx)*1.2)-(Math.abs(b.top-qLine.top)+Math.abs(b.cx-qLine.cx)*1.2))[0];const cluster=candidates.filter(l=>Math.abs(l.cx-nearest.cx)<=140&&Math.abs(l.top-nearest.top)<=52).sort((a,b)=>a.top-b.top||a.left-b.left).slice(0,3),text=clean(cluster.map(l=>l.titleText).join(' '));return letters(text)>=5&&text.length<=120?{text,conf:Math.min(...cluster.map(l=>l.titleConf)),lines:cluster.map(l=>l.titleText)}:{text:nearest.titleText,conf:nearest.titleConf,lines:[nearest.titleText]}}
function parse(page:any){const ls=lines(Array.isArray(page.words)?page.words:[]),out:any[]=[];const prices=ls.map(l=>({l,p:directDecimal(l.text)})).filter(x=>x.p!==null&&x.l.maxHeight>=40&&x.l.priceConf>=60&&!unitMarker(x.l.text)&&!promo(x.l.text));for(const{l:pl,p}of prices as any[]){const local=ls.filter(l=>l!==pl&&Math.abs(l.cx-pl.cx)<=165&&l.top>=pl.top-210&&l.top<=pl.bottom+235),quantities=local.map(l=>({l,q:qty(l.text),d:Math.abs(l.cx-pl.cx)*1.4+Math.abs(l.top-pl.top)})).filter(x=>x.q&&x.l.conf>=65&&x.l.maxHeight<=45).sort((a,b)=>a.d-b.d);if(!quantities.length)continue;const q=quantities[0];if(Math.abs(q.l.top-pl.top)>220)continue;const title=buildTitle(local,pl,q.l);if(!title)continue;out.push({page:page.page_number,title:title.text,price:p,quantity:q.q,price_mode:'direct-decimal',conf:{page:Number(page.avg_confidence||0),price:Math.round(pl.priceConf),title:Math.round(title.conf),qty:Math.round(q.l.conf)},raw:{price_line:pl.text,title_lines:title.lines,qty_line:q.l.text,price_height:pl.maxHeight,coords:{p:[pl.left,pl.top,pl.right,pl.bottom],q:[q.l.left,q.l.top,q.l.right,q.l.bottom]}}})}const seen=new Set<string>();return out.filter(x=>{const k=`${page.page_number}|${norm(x.title)}|${x.price}|${x.quantity}`;if(seen.has(k))return false;seen.add(k);return true})}
Deno.serve(async req=>{if(req.method!=='POST')return J({error:'method'},405);if(!ok(req))return J({error:'auth'},401);const b=await req.json().catch(()=>({})),id=String(b.import_id||'d55d2c80-2e39-4946-89a7-f52bfe567822'),engine=String(b.engine||'tesseract-cli-ces-jip-v2');const{data,error}=await db.from('leaflet_ocr_pages').select('page_number,avg_confidence,words,engine').eq('import_id',id).eq('engine',engine).order('page_number');if(error)return J({error:error.message},500);const pages=data||[];if(pages.length!==12||new Set(pages.map((p:any)=>p.page_number)).size!==12)return J({ok:false,error:`expected 12 OCR pages for ${engine}, got ${pages.length}`},409);const all=pages.flatMap((p:any)=>parse(p));return J({ok:true,adapter:'jip-main-price-v5-direct-only-debug',import_id:id,engine,count:all.length,candidates:all})});
